### ISSUE TITLE
Linter para C en Windows

### ISSUE THREAD

**Issue by cacosandon** [IIC2133-PUC/2019-2#1]
Hola!

Quería saber si existe alguna opción de Linter para C si tengo Windows Subsystem.

Muchas gracias!

**Comment by alopez7** [comment]
Hola, 
Te puedo contar lo que uso yo en atom pero creo que hay paquetes similares en visual studio.
Uso los paquetes:
* linter
* linter-clang
* autocomplete-clang

Tanto linter-clang como autocomplete-clang te van a pedir un path para clang para usarlo correctamente. El problema es que clang está instalado en el linux sub system y no en windows. Para solucionarlo lo que hice fue instalar msys2 en windows. Esto es una colección de cosas de linux para usar en windows tales como clang. La página oficial de msys2 es [esta](www.msys2.org). Una vez instalado usé la consola de msys2 para instalar clang. Finalmente el path en el que clang quedó en windows es C:/msys64/mingw64/bin/clang.exe **OJO:** Este path depende de donde instalaste msys en tu computador.
