### ISSUE TITLE
[Tarea 0] Duda estructuras a usar

### ISSUE THREAD

**Issue by FJavierOss** [IIC2133-PUC/2019-2#10]
Hola, la duda que tengo es respecto a que es lo que se espera que estructuras debemos ocupar para esta tarea. El punto es, ¿se espera que hagamos uso de la estructura Image provista en el código de la tarea e interactuar solamente con esta o que nosotros creemos nuestra propia estructura que posteriormente interactue con la estructura Image para generar la imagen final?
Gracias anticipadamente.
Saludos

**Comment by ignaciohermosillacornejo** [comment]
Queda a tu libre disposición.

Lo único que nos interesa es que la imagen final que guardas sea identica a la que esperamos, todo el resto depende de tí y como te acomode más trabajar.

Saludos

**Comment by FJavierOss** [comment]
Gracias
