### ISSUE TITLE
Donde se ven las notas del ramo?

### ISSUE THREAD

**Issue by naoliden** [IIC2133-PUC/2019-2#102]
Donde se ven las notas del ramo?

**Comment by alopez7** [comment]
Las notas de interrogaciones las puedes ver [aquí](https://docs.google.com/spreadsheets/d/1GOWUO8IHKROCYkWDARo87potapqSSFSqYlrXfuxk5cU/edit?usp=sharing) y las de las tareas [aquí](https://docs.google.com/spreadsheets/d/1iukfBCX6dq2oGMZJp_mcEtMBCb0Qxw6EkJTKKXDfyts/edit?usp=sharing).
