### ISSUE TITLE
Posibilidad de grabar las clases

### ISSUE THREAD

**Issue by frduran** [IIC2133-PUC/2019-2#103]
Hola! En algunos ramos están grabando las clases o transmitiéndolas de forma online. Existe la posibilidad de que ustedes también lo hagan?
Saludos!

**Comment by alopez7** [comment]
Hola,

Me encantaría si me puedes contar cómo es la modalidad exacta que están haciendo los otros cursos para ver si podemos implementar algo como eso. ¿Están haciendo la clase online? ¿La graban en sus casas y la envían? ¿La hacen presencial y además la graban?

**Comment by frduran** [comment]
El profesor está haciendo la clase presencial y también la transmite por la plataforma zoom para dar la posibilidad de ver la clase online a quienes les complica asistir. Zoom tiene chat por lo que los que tienen dudas las escriben ahí y el profe las iba respondiendo a medida que avanzaba.
Tengo entendido que zoom permite grabar, pero no estoy del todo segura como funciona esta parte.
Gracias de antemano!

**Comment by sormazabal** [comment]
Hola! Grabé el audio de la clase del Lunes. Lo subí a un [Drive](https://drive.google.com/open?id=1KPi3zY2ivVjWHg8TbPpJnkgfY-NXf0a8)
Espero que te sirva!

**Comment by alopez7** [comment]
Mañana me reuno con Yadran y se lo voy a proponer. Gracias Sofía por el audio

**Comment by frduran** [comment]
Muchas gracias Sofía!
