### ISSUE TITLE
Dudas sobre el enunciado de la Tarea 3

### ISSUE THREAD

**Issue by sormazabal** [IIC2133-PUC/2019-2#104]
Hola!
Estoy algo confundida con respecto a lo que hay que implementar y lo que está hecho en la tarea.
1. ¿Tenemos que implementar un algoritmo que dibuje distritos de modo de que Kodos salga ganando la elección?
2. Tomando lo anterior como cierto, ¿tenemos que ir probando respuestas usando los métodos de packing y cracking y entre todas las posibles combinaciones que nos entregue cada método elegir la mejor?

Espero que se encuentren bien :worried:

**Comment by alopez7** [comment]
1. Hay que implementar backtracking para elegir los distritos que hacen que gane Kodos considerando que cada distrito debe tener el mismo número de personas y que cada distrito tiene que estar conectado a si mismo.

2. Los métodos de cracking y packing se explicaron solo para explicar mejor qué es gerrymandering pero no es el objetivo de la tarea.

Se espera que la solución implementada por ustedes sea backtracking de la manera más simple posible, esto quiere decir que no se espera que hagan podas ni heurísticas.

La forma en la que debería funcionar el programa es simplemente asignar a cada celda un distrito y revisar si cumple con las restricciones.

Espero responda tu pregunta. No dudes en preguntar si tienes más dudas

**Comment by sormazabal** [comment]
@alopez7 
La solución encontrada debe cumplir sólo con ser solución al problema o debe ser la **mejor** solución?

**Comment by ignaciohermosillacornejo** [comment]
Solo debe ser solución

**Comment by jfpena1** [comment]
Hola, queria saber que decision debe tomarse en caso de que un distrito quede con igual cantidad de votos por A que por B, quien gana? Supongo que dado que queremos que gane KODOS, asumimos que en caso de 50-50 el es el ganador. 
Muchas gracias

**Comment by alopez7** [comment]
En ese caso no gana ninguno de los 2 partidos en el distrito. Además si el resultado final del mapa completo es un empate, no sirve como estado solución del problema porque no gana kodos.

**Comment by jfpena1** [comment]
gracias!

**Comment by ignaciohermosillacornejo** [comment]
El número de distritos es fijo. Si el número de distritos es _k_, debes hacer _k_ distritos.

**Comment by jfpena1** [comment]
Hola, al tratar de correr la tarea tal y como se nos entrega, me tira segmentation fault, por un 
```invalid read of size 4``` en el fscanf() del height y width del ```main```.  
Saben porque podria estar pasando esto?
Gracias

**Comment by alopez7** [comment]
Revisa que el path al archivo es correcto. También puedes comparar el objeto tipo FILE para ver si es nulo. Si es nulo entonces no se abrió correctamente el archivo

**Comment by augustoas** [comment]
Solo se trabaja en solver/main.c? el resto no hay que modificarlo? saludos

**Comment by alopez7** [comment]
Hola, puedes trabajar en todos los archivos de la carpeta solver

**Comment by francisca1** [comment]
Hola!, si en se deben hacer 3 distritos y en 2 hay empate y en uno gana kodos, cuenta como solución verdad? gracias.

**Comment by alopez7** [comment]
Si, cuenta como victoria

**Comment by gatochico** [comment]
Hola! Para esta tarea se evaluará el liberar toda la memoria usada, o no es necesario preocuparse de esa parte?

**Comment by alopez7** [comment]
No es parte de la nota pero puede que se de un bonus minúsculo

**Comment by Pipelao** [comment]
Hola,

Tengo una pregunta acerca de la cantidad de personas que hay, no sé de dónde  obtener esta info, ya que en el enunciado dice que la cantidad de personas es diferente a la cantidad de celdas.

Gracias.

**Comment by alopez7** [comment]
Hay una persona como máximo por celda, y se cumple siempre que el número de personas es divisible por el número de distritos.

**Comment by ignaciohermosillacornejo** [comment]
Hola @Pipelao 

Tienes que contar desde el tablero el número de personas si quieres obtener ese número.

**Comment by Pipelao** [comment]
Hola @alopez7 y @ignaciohermosillacornejo 

Aún no lo gro entender. En el caso que la celda sea del tipo EMPTY tiene 0 personas, y si es del resto, ya sea NONE, PARTY_A, PARTY_B si o si hay una persona por celda o puede ser que no haya?

Gracias

**Comment by alopez7** [comment]
Sies empty, no hay nadie. Si es None, hay una persona que no bota y si hay party_a o party_b, es un botante de la party correspondiente

**Comment by akrebs2** [comment]
Hola!

Si en un distrito se obtiene una mayoría menor que el 50%, gana igual? Por ej: 2A, 1B, 10 EMPTY, gana A?

Gracias

**Comment by alopez7** [comment]
Si, gana A

**Comment by akrebs2** [comment]
Perfecto. Otra duda, todas las celdas tienen que tener asignado un distrito?

**Comment by alopez7** [comment]
Si, todas

**Comment by francisca1** [comment]
Hola, los tests dados, son todos para la funcionalidad básica de la tarea? o también hay algún test que requiera podas?

**Comment by alopez7** [comment]
Los tests que les pasamos incluyen la parte básica y el bonus. La división exacta no la tengo muy clara pero seremos generosos en ese sentido :)

**Comment by beayancan** [comment]
Un par de dudas,
- ¿Siempre habrá una forma de distribuir los distritos de tal forma que kodos gane o puede que en algún test no exista solución?
- Además, respecto a lo de que todas las celdas (vacias o con votantes) se les debe asignar un distrito ¿Se permite que un distrito solo se compone de celdas sin votantes?

**Comment by alopez7** [comment]
Siempre puede ganar kodos. Todas las celdas deben tener distrito, incluso las vacías. Todo distrito debe tener el mísmo número de personas aunque no voten.

**Comment by beayancan** [comment]
Gracias

**Comment by gatochico** [comment]
Hola! Con respecto al output esperado, debemos hacer que la interfaz muestre tan solo la solución del problema (la distribución final de los distritos), o tenemos que seguir el ejemplo que venía en main y mostrar paso a paso todas las asignaciones/desasignaciones del algoritmo? Gracias!

**Comment by ignaciohermosillacornejo** [comment]
Hola @gatochico 

Solo tienes que mostrar la etapa final, no son necesarios los pasos intermedios aunque no hay problema en que esten los pasos intermedios.

**Comment by sormazabal** [comment]
Para ganar Kodos tiene que ganar con:
1) La mitad + 1 de todas las personas del distrito contando los que no votan.
o
2)La mitad + 1 de todas las personas del distrito contando solo los que votan?

**Comment by alopez7** [comment]
Contando solo los que votan

**Comment by gatochico** [comment]
Hola! Para que el programa tenga el formato de output de la respuesta correcto, solo basta que use watcher_close() al final? Por otro lado, hice que cada distrito se coloree en la interfaz con el candidato ganador de ese distrito, esto interfiere con la correccion de la tarea (para sacarlo si es así)? Gracias!

**Comment by ignaciohermosillacornejo** [comment]
Hola @gatochico 
Estas en lo correcto, usa watcher_close() al final y el juez va a corregir lo que estaba en la pantalla en ese instante. Los colores no son relevantes para el juez y estaban para darles una ayuda visual al hacer su tarea, lo unico importante es los valores de los distritos en la interfaz al momento de llamar watcher_close().

Extendiendome un poco más, lo que hace el juez es
1. Cambiar el archivo watcher por uno distinto, el watcher nuevo lo que hace es que escribe en un archivo de texto todas las llamadas que se hagan (en vez de pasarselas al beholder como se hace actualmente)
2. Compilar y ejecutar tu código
3. Si tu codigo no se cae y se demora menos de 10 segundos, el juez analiza el archivo de texto generado, junto con la configuración original del tablero y determinar si tu solición es valida o no.

**Comment by tomascortes** [comment]
Hola, no es precisametne de enunciado, pero estoy utilizando una estrategia similiar al del ejemplo de las reinas y mi programa encuetra la solucion pero se demora **demasiado** incluso para el test_00, y haciendo algunas podas, es esto normal y debería usar otro método?, o si hiciera bien las podas  debería funcionar??
gracias!

**Comment by alopez7** [comment]
Deberías poder resolverlo eficiente mente con una modelación simple. Preocúpare de que revisar si una asignación es válida sea eficiente ya que esta operación va a ser la que se ejecute más veces en tu programa.

**Comment by gatochico** [comment]
@ignaciohermosillacornejo Una última duda al respecto con watcher_close(): Me ocurre que si no incluyo esta línea y luego ejecuto `time ./solver tests/test_00.txt` (cualquier test), el programa automáticamente termina, me calcula el tiempo de ejecución, y queda la interfaz abierta hasta que la cierre. Sin embargo, cuando agrego watcher_close() y corro `time ./solver ...` en la consola, el programa no me calcula el tiempo de ejecución ni termina completamente de correr hasta que yo cierre el tablero final a mano. ¿Está bien que pase esto, o es algún problema de mi código? :(

**Comment by alopez7** [comment]
Eso es un problema de la librería cairo, no te preocupes.

**Comment by Reyza96** [comment]
Hola, no es una dudad de enunciado propiamente tal y se parece a la que hizo @tomascortes. También pasa que mi programa se esta demorando demasiado pero solo para el test_03 en adelante. Los primeros tres los resuelve instantáneamente. Podría ser que esto pase debido  la interfaz y una vez que esta se saque se demoraría menos?
