### ISSUE TITLE
Guía de Backtracking

### ISSUE THREAD

**Issue by alopez7** [IIC2133-PUC/2019-2#105]
Está lista la guía de backtracking, la pueden encontrar en la carpeta de los talleres. Cualquier duda de la guía la pueden hacer acá. Perdón por la demora.

**Comment by Kitaps** [comment]
Hola, 

en que carpeta está? O bajo que nombre?

Graciass

**Comment by ignaciohermosillacornejo** [comment]
Hola @Kitaps 

La guia la puedes encontrar en: `2019-2/Talleres/Taller 4 - Backtracking/taller.md`
También puedes pinchar [acá](https://github.com/IIC2133-PUC/2019-2/blob/master/Talleres/Taller%204%20-%20Backtracking/taller.md)

Saludos

**Comment by Kitaps** [comment]
Ahh gracias, estaba buscando en guias jaja
gracias

**Comment by gatochico** [comment]
Hola! ¿La guía está completa? Pareciera que a la sección de variables auxiliares le faltara contenido :o 
Gracias de antemano

**Comment by ignaciohermosillacornejo** [comment]
Falta completar esa parte, va a estar prontamente. Preferimos publicarla sin terminar antes que demorar más la entrega, si siguies la guia y vez los códigos de ejemplo vas a tener una muy buena idea de que hacer para la tarea

**Comment by alopez7** [comment]
Hola, la subí incompleta para que la tengan lo antes posible. La próxima semana haremos una sesión de ayuda para resolver dudas de la tarea con los ayudantes para compensarlo.

Sobre la sección de variables axuliares: una variable auxiliar te permite acelerar ciertas operaciones al hacer backtracking, por ejemplo en la tarea es posible crear contadores para cada distrito para saber cuantos votantes de cada tipo tienen en cada momento. Esto permite determjnar rápidamente si un distrito está completo o no.

**Comment by gatochico** [comment]
Ok, gracias por la respuesta rapida!
