### ISSUE TITLE
[clases][Programación dinámica] arreglo m a solución

### ISSUE THREAD

**Issue by Kitaps** [IIC2133-PUC/2019-2#107]
Hola, en la clase sale que para encontrar la solución usamos el arreglo m.

Pero el arreglo m solo tiene los valores acumulados de los valores que están adentro. 

Cómo llegamos de eso a la solución que da esos valores?

**Comment by alopez7** [comment]
Hola @Kitaps, el arreglo m puede a veces ayudarte a construir la solución de manera eficiente dependiendo del problema. Otras veces es más cómodo crear un arreglo auxiliar que te permita construir la solución directamente. Si me dices un problema yo te puedo decir cómo se puede usar m y como se puede usar un arreglo auxiliar.

**Comment by Kitaps** [comment]
Hola, sorry la demora: 
Un ejemplo que se me ocurre podría ser este: 

Sean el formato: 
n i)   s-f   v

Tal que: 
n   es el nombre de la función
i   es el indice de la función
s   el tiempo de inicio (es inclusivo ( "[" ) )
f   el tiempo final (es exclusivo ( ")" ) ) 
v   el valor de esa función

a 1)   0-2   1
b 2)   0-3   2                                  
c 3)   2-4   3                                   
d 4)   3-4   4                                  

Quedaríamos entonces con el arreglo ordenado según f:
a - b - c - d           con los tiempos finales respectivos
2 - 3 - 4 - 4

luego si revisamos los b(*) obtenemos que: 
b(1) = 0
b(2) = 0
b(3) = 1    (a)
b(4) = 2    (b)

Si buscamos los opt entonces obtenemos que:
opt(a) = opt(1) = max{ 1 + ( opt(0)=0 ), ( opt(0)=0 ) } = 1
opt(b) = opt(2) = max{ 2 + ( opt(0)=0 ), ( opt(1)=1 ) } = 2
opt(c) = opt(3) = max{ 3 + ( opt(1)=1 ), ( opt(2)=2 ) } = 4
opt(d) = opt(4) = max{ 4 + ( opt(2)=2 ), ( opt(3)=4 ) } = 6

Por lo que quedamos con un m = [ 1, 2, 4, 6]

Igual de aquí veo que es facil sacar que valores entran a la solución, pero porque lo hice a mano, pero mi pregunta es, si es que lo hace un programa y este solo te retorna el m, como sabes a partir de ese que la solución optima es "b - d" ? 

Gracias por el tiempo, y si tengo algún error porfa haganmelo saber :)

**Comment by alopez7** [comment]
En cada problema la manera de interpretar m es distinta. Fíjate que se construyó con esa función opt. Si conoces la función opt entonces sabes al mirar m cuál es el máx. Por lo tanto sabes cual es la solución. Puedes además generar un arreglo aparte para almacenar esa información y simplemente guardar que en esa llamada recursiva escogiste b o escogiste c y así.

**Comment by Kitaps** [comment]
La idea de generar un arreglo para ir almacenando la información me hace sentido. 

Pero aun no entiendo eso: 

> Si conoces la función opt entonces sabes al mirar m cuál es el máx. Por lo tanto sabes cual es la solución.

Yo se cuales son los b porque los calculé a mano (y los guardé) y se las soluciones de cada opt porque lo hicce a mano (y lo guardé). 

Pero si tengo solamente las las funciones (de a hasta d) y la función opt que luego de ejecutarse recursivamente me entrega m. Como solo a partir del m obtengo la solución (como dice en la clase).

![image](https://user-images.githubusercontent.com/10112117/69496948-659f5900-0eb6-11ea-869a-1f3cedcae17f.png)

**Comment by alopez7** [comment]
Ok, mirando el arreglo m = [1, 2, 4, 6] de tu ejemplo, puedes ver que el último valor es 6, por lo que se puede tener una ganancia de 6. El algoritmo calculó ese 6 calculando max(v_j + m[b(j)], m[j-1]). Tu conoces los valores v_j, m[b(j)] y m[j-1] por lo que puedes saber cual es efectivamente la tarea que se agregó y por lo tanto te llevó al resultado 6. Luego, sabiendo cual elegiste, puedes seguir analizando el arreglo m para reconstruir la solución de la misma manera.

Por otro lado, podemos construir un arreglo s para almacenar la solución de manera más simple: Digamos que en  el algoritmo, luego de la línea  m[j] = max{ vj + rec-opt(b(j)) , rec-opt(j-1) } guardamos en s[j] 1 si escogimos vj + rec-opt(b(j)) y 0 si escogimos rec-opt(j-1). Este arreglo va a decirnos exactamente si el elemento j está o no en la solución si hay un 1 y que no está en la solución si hay un 0.

Espero te sirva

**Comment by Kitaps** [comment]
Ya gracias, ahora entiendo. 
Gracias por tu tiempo.
