### ISSUE TITLE
[Tarea 3] - Make

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2133-PUC/2019-2#108]
Hola, al hacer el comando `make` me sale el siguiente error:

```
No se encuentra el archivo: *.h
No se encuentra el archivo: *.h
No se encuentra el archivo: *.c
FIND: formato de parámetros incorrecto
gcc: error: `pkg-config: No such file or directory
gcc: error: gtk+-3.0`: No such file or directory
gcc: error: unrecognized command line option '--cflags'
gcc: error: unrecognized command line option '--libs'
Makefile:121: recipe for target 'beholder' failed
make: *** [beholder] Error 1
```
¿Qué puede ser?

**Comment by alopez7** [comment]
En que carpeta estás haciendo make? Modificaste algo del código?

**Comment by VicenteVicente** [comment]
En la carpeta `T3-2019-2-{mi usuario}`. No he modificado absolutamente nada :/

**Comment by alopez7** [comment]
Chuta, y en qué sistema operativo estás trabajando?

**Comment by VicenteVicente** [comment]
En Windows 10

**Comment by alopez7** [comment]
Pero estás usando una virtual box o tienes linux en la consola?

**Comment by VicenteVicente** [comment]
Ocupo MinGW si mal no recuerdo, lo ejecuto desde una Powershell

**Comment by alopez7** [comment]
A decir verdad no tengo idea por qué falla de esa forma. ¿Has tenido problemas del estilo antes?

**Comment by VicenteVicente** [comment]
Nunca en la vida :/, qué puedo hacer?

**Comment by alopez7** [comment]
Puedes instalar una máquina virtual e i tentar hacer la tarea ahí

**Comment by VicenteVicente** [comment]
Ok, pero podrían revisar en el Makefile si hay algún conflicto para las rutas de Windows, quizá estas haya que ponerlas de alguna otra forma?

**Comment by vichoeq** [comment]
El codigo lo escribimos en windows y de ahi lo probamos en las otras plataformas. Lo que pasa es que MinGW está deprecado: por eso dijimos que usen Linux Subsystem.
