### ISSUE TITLE
[Tarea 3] - Cairo

### ISSUE THREAD

**Issue by beayancan** [IIC2133-PUC/2019-2#109]
Estoy utilizando macOS Mojave 10.14.6 (18G1012)

Intentado hacer `make`, me aparece que el paquete `cairo-pdf.h` y `cairo.h` no se encuentra a pesar de que fue instalado

Al hacer make
```
/bin/sh: /usr/local/bin/pkg-config: Permission denied
clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -lpng: 'linker' input unused [-Wunused-command-line-argument]
src/beholder/drawing/drawing.c:4:10: fatal error: 'cairo-pdf.h' file not found
#include <cairo-pdf.h>
         ^~~~~~~~~~~~~
1 error generated.
make: *** [obj/beholder/drawing/drawing.o] Error 1
```

Lo instalé usando [esta guía](http://macappstore.org/cairo/) pero me sigue apareciendo el mismo problema. Al buscar donde estaba me aparece que sí está instalado

![Captura de Pantalla 2019-11-23 a la(s) 21 53 10](https://user-images.githubusercontent.com/37157874/69487606-ab6b0b80-0e3b-11ea-8464-4fefc47ba55d.png)

Quería saber si saben qué podría estar pasando, gracias

**Comment by beayancan** [comment]
Me ocurre algo similar cuando intento hacer make del taller 4, ahora con la libería `gtk/gtk.h`

![Captura de Pantalla 2019-11-24 a la(s) 12 51 40](https://user-images.githubusercontent.com/37157874/69497213-38a07580-0eb9-11ea-8235-b8e76171e5b0.png)

**Comment by alopez7** [comment]
Tienes gtk instalado? es la librería para la interfaz gráfica. Se usó para la tarea anterior

**Comment by beayancan** [comment]
Sí está instalado. Para la tarea 2 funcionaba, pero este es otro computador

![Captura de Pantalla 2019-11-24 a la(s) 14 10 38](https://user-images.githubusercontent.com/37157874/69498240-3db6f200-0ec4-11ea-9f4d-5070e202aca7.png)

**Comment by vichoeq** [comment]
Hola,

Para lo del `#include <cairo-pdf.h>`, borra esa línea nomás, quedó de un código que ya no usamos. Lo siento.

> Sí está instalado. Para la tarea 2 funcionaba, pero ahora ocupo otro computador

Veo que los archivos están en el computador... Cual es el output del comando `pkg-config --cflags --libs gtk+-3.0` ???

**Comment by beayancan** [comment]
No me permite acceder, pero el package está en la siguiente direccion 

![Captura de Pantalla 2019-11-24 a la(s) 15 54 26](https://user-images.githubusercontent.com/37157874/69499624-bf158100-0ed2-11ea-91b9-621fb094a840.png)

**Comment by VicenteVicente** [comment]
Hola, instalé Linux en mi computador para evitar el [problema con `make` en Windows 10](https://github.com/IIC2133-PUC/2019-2/issues/108) y ahora me ocurre esto mismo :/

**Comment by beayancan** [comment]
Pude solucionarlo y compilar el taller 4 y la base de la tarea, el problema no era `cairo` ni  `gtk` sino que `pkg-config`. A pesar que ya lo tenía instalado parece que tenía unos problemas, por lo que se solucionó ejecutando

```
brew reinstall pkg-config
```

**Comment by alopez7** [comment]
> Hola, instalé Linux en mi computador para evitar el [problema con `make` en Windows 10](https://github.com/IIC2133-PUC/2019-2/issues/108) y ahora me ocurre esto mismo :/

¿Pero el problema que tienes ahora es el mismo o es un error distinto? ¿Podrías mandarme un screenshot de tu consola cuando haces make?

**Comment by VicenteVicente** [comment]
Disculpa, logré solucionarlo era un problema de la ruta en donde se había instalado GTK en Linux. De todos modos sería muy útil si se pudiese arreglar la tarea para que funcione correctamente en Windows!

**Comment by Jaluco** [comment]
Hola, me sale que cairo.h no existe en el directorio :( no he encontrado una solucion en google, alguien sabe que hacer?

**Comment by alopez7** [comment]
Eso te sale al compilar o te lo indica el editor de texto?

**Comment by Jaluco** [comment]
al compilar con make

**Comment by Jaluco** [comment]
Logre solucionarlo :)

**Comment by alopez7** [comment]
Cual era el probloblema?
