### ISSUE TITLE
[Taller 4] Orden asignaciones

### ISSUE THREAD

**Issue by Kitaps** [IIC2133-PUC/2019-2#110]
Hola, 

en la guía sale que: 

> Si estan confundidos podemos ir paso a paso. Tenemos que asignar A, B y C. Si comienzo con A, ¿Cuantas asignaciones son posibles? Bueno dos, A=0 o A=1. Siguiendo con B, dado que asigne A a alguna variable, ¿Cuantas asignaciones son posibles? Dos nuevamente? Bueno si A=0, B puede tiene dos asignaciones posibles y si A=1, B también tiene dos asignaciones posibles, por lo que en total son 4. Repitiendo nuevamente para C, tenemos 8 asignaciones más posibles, dependiendo de las combinaciones de A y B anteriores, por lo que en total tenemos 2 + 4 + 8 = 14.

No me queda claro como se llega al 2 y al 4.
Lo que pienso podría ser es que para 2 sea que solo se decide asignarle valores a una variable (A) y las otras no. L mismo para 4, donde solo se le asigna a dos variables (A y B). 
Pero si ese fuese el caso, ahí igual importaría el orden (la variable a la que se le asigna un valor del dominio). Es decir no es lo mismo solo asignarle un valor solo a A, que solo a B, lo mismo con las combinaciones (los casos que dan 4). 

Gracias

**Comment by alopez7** [comment]
Lo que pasa es que se está contando cuantas veces se asigna el valor de una variable. En ese caso se está asignando un valor a A, luego a B y luego a C. Si ves la ejecución completa de las asignaciones sería algo así:

Asignar A = 0
  Asignar B = 0
    Asignar C = 0
    Desasignar C
    Asignar C = 1
    Desasignar C
  Desasignar B
  Asignar B = 1
    Asignar C = 0
    Desasignar C
    Asignar C = 1
    Desasignar C
  Desasignar B
Desasignar A
Asignar A = 1
  Asignar B = 0
    Asignar C = 0
    Desasignar C
    Asignar C = 1
    Desasignar C
  Desasignar B
  Asignar B = 1
    Asignar C = 0
    Desasignar C
    Asignar C = 1
    Desasignar C
  Desasignar B
Desasignar A

Si cuantas cuantas veces se asigna A son solo 2, y su cuentas para B son solo 4 y finalmente para C son 8

**Comment by Kitaps** [comment]
Yaa perfecto, había entendido mal a lo que se refieren con asignación. Ahora me quedó clarisimo. 
Muchas gracias!!
