### ISSUE TITLE
[clases] Presencialidad de las clases

### ISSUE THREAD

**Issue by Jaluco** [IIC2133-PUC/2019-2#111]
Hola, quisiera saber que tan escencial sería para lo que queda del desarrollo del curso, pues me complica un poco asistir, creo que habían enviado un mail al respecto hace un tiempo pero no he podido encontrarlo

**Comment by alopez7** [comment]
Transmitiremos el curso de manera online a través de zoom además de hacer la clase de manera presencial, ya les daremos las indicaciones de como conectarse a la clase.
