### ISSUE TITLE
[Tarea 3] Memory Leaks

### ISSUE THREAD

**Issue by daleal** [IIC2133-PUC/2019-2#113]
Hola! Escribo esta issue porque me ocurre que al compilar y ejecutar el código base con un test cualquiera, valgrind arroja muchos leaks y quería saber si debería preocuparme o si es lo esperado (la animación con los bloques llenándose y luego con los distritos coloreándose si ocurre).

![memory-leaks](https://user-images.githubusercontent.com/37158127/69504359-cfdceb80-0f00-11ea-86ac-fc497701192b.png)

Eso es lo que dice valgrind (el `id` después del nombre del repo en la consola es porque descargué el último commit que se nos entregó para que no influyera nada de lo que hice después).

**Comment by alopez7** [comment]
Mmmm, lo voy a revisar. Igual no te preocupes porque no se evalúa que se libere toda la memoria en esta tarea

**Comment by daleal** [comment]
Gracias!
