### ISSUE TITLE
interfaz grafica

### ISSUE THREAD

**Issue by jfpena1** [IIC2133-PUC/2019-2#114]
Hola, me pasa que no se me muestra nada de la interfazz grafica. Mi SO es windows y tengo linux subsystem. Para la tarea pasada si me funcionaba la interfaz y ahora no aparece. Luego de hacer bash hago ```export DISPLAY=:0```, pero nose si esta sirviendo.

Muchas gracias.

**Comment by alopez7** [comment]
Y abriste xming?

**Comment by jfpena1** [comment]
como se abre?

**Comment by alopez7** [comment]
Instalas el programa y simplemente lo ejecutas como cualquier otro (los buscas en el inicio de windows).

**Comment by jfpena1** [comment]
gracias! ahi me funciono
