### ISSUE TITLE
Dudas I3 parte 2 pregunta 1 (programación dinámica)

### ISSUE THREAD

**Issue by alopez7** [IIC2133-PUC/2019-2#115]
Acá hagan las dudas que tengan de la pregunta 1

**Comment by alopez7** [comment]
Subo la pregunta en PDF por si les acomoda
[Interrogación 3 parte 2 pregunta 1.pdf](https://github.com/IIC2133-PUC/2019-2/files/3888576/Interrogacion.3.parte.2.pregunta.1.pdf)

**Comment by sormazabal** [comment]
![image](https://user-images.githubusercontent.com/7980453/69582207-da59bc80-0fb6-11ea-9c95-d7eac7a54ef4.png)
No entiendo por qué el dibujo de la izquierda no es óptimo, si el nodo de 2000 de más a la derecha (entre 1000 y 4000) no está conectado con ningún otro nodo verde. ¿Es un error del dibujo o entendí mal la regla?

**Comment by francisca1** [comment]
es porque suma 9500, y se quiere el que sume más.

**Comment by francisca1** [comment]
Hola, cual es la cantidad maxima de hijos por nodo? 2 ? o puede existir cualquier cantidad ?

**Comment by francisca1** [comment]
Otra pregunta, a que se refieren en la pregunta  C ? (C. Explica cual es el orden natural en el que se deberían solucionar los subproblemas para llegar a la solución final. ), de donde se debe partir solucionando el problema para tener los subsproblemas (hojas, raiz, nodo aleatorio , etc)?

**Comment by alopez7** [comment]
> ![image](https://user-images.githubusercontent.com/7980453/69582207-da59bc80-0fb6-11ea-9c95-d7eac7a54ef4.png)
> No entiendo por qué el dibujo de la izquierda no es óptimo, si el nodo de 2000 de más a la derecha (entre 1000 y 4000) no está conectado con ningún otro nodo verde. ¿Es un error del dibujo o entendí mal la regla?

Es por lo que dice tu compañero, hay una solución que suma más por lo que esta solución no es óptima. Es una invitación válida pero no la mejor.

**Comment by alopez7** [comment]
> Hola, cual es la cantidad maxima de hijos por nodo? 2 ? o puede existir cualquier cantidad ?

Puede tener una cantidad indefinida de hijos



> Otra pregunta, a que se refieren en la pregunta C ? (C. Explica cual es el orden natural en el que se deberían solucionar los subproblemas para llegar a la solución final. ), de donde se debe partir solucionando el problema para tener los subsproblemas (hojas, raiz, nodo aleatorio , etc)?

Lo que pasa es que para solucionar un problema grande hay que resolver problemas más pequeños que lo compongan, llamemos a los subproblemas más pequeños requisitos. La pregunta es: Dados todos los subproblemas posibles dado un árbol, ¿cuál es el orden en que se deben resolver los subproblemas de manera de tener siempre los requisitos previamente resueltos? Ese es el orden natural de los subproblemas

**Comment by tomascortes** [comment]
Hola, leí los ppt y quizá me salte esta parte pero no entiendo a que se refiere la D con agregar una tabla, esta es para guardar los valores que ya he calculado?

**Comment by gatochico** [comment]
Hola! En la parte C), puedo asumir que tengo una estructura de datos que ya almacena al padre y a los hijos de cada nodo (y por ejemplo llamar a x.parent/x.descendants)?

**Comment by alopez7** [comment]
> Hola, leí los ppt y quizá me salte esta parte pero no entiendo a que se refiere la D con agregar una tabla, esta es para guardar los valores que ya he calculado?

Si te fijas en la clase 19 (PD parte 1) hay una diferencia grande entre la diapo 19 y la 24. Se agrega la tabla m para hacer más eficiente el algoritmo. Se pide que hagas lo mismo para este problema.

**Comment by alopez7** [comment]
> Hola! En la parte D), puedo asumir que tengo una estructura de datos que ya almacena al padre y a los hijos de cada nodo (y por ejemplo llamar a x.parent/x.descendants)?

Si, asume que el árbol viene de la manera que más te acomode.

**Comment by cacosandon** [comment]
Podemos asumir que un nodo tendrá un solo padre?

**Comment by alopez7** [comment]
> Podemos asumir que un nodo tendrá un solo padre? O bien que un empleado tiene un solo jefe directo?

Si

**Comment by jpjoublan** [comment]
En la parte B, cuando nos piden que demostremos que la cantidad de subproblemas son polinomiales con respecto al número de nodos del árbol, se refiere a la cantidad de subproblemas **distintos** a resolver o se refiere a la cantidad **total** de subproblemas que tengo que resolver para encontrar la solución?

**Comment by marioreinike** [comment]
Hola! en la parte C no menciona que debemos escribir un algoritmo para resolver el problema, sin embargo en la D se habla del algoritmo anterior. Entonces es necesario escribir el algoritmo? O la D se puede explicar en palabras cómo aplicar la tabla?

**Comment by alopez7** [comment]
> En la parte B, cuando nos piden que demostremos que la cantidad de subproblemas son polinomiales con respecto al número de nodos del árbol, se refiere a la cantidad de subproblemas **distintos** a resolver o se refiere a la cantidad **total** de subproblemas que tengo que resolver para encontrar la solución?

Hola, la cantidad de subproblemas distintos

**Comment by alopez7** [comment]
> Hola! en la parte D no menciona que debemos escribir un algoritmo para resolver el problema, sin embargo en la E se habla del "algoritmo anterior". Entonces es necesario escribir el algoritmo? O la D se puede explicar en palabras cómo aplicar la tabla?

Hola, la función recursiva que resuelve el problema en la parte D es un algoritmo.

**Comment by naoliden** [comment]
El jefe de la empresa (nodo raiz del arbol) tiene que ser si o si invitado?

**Comment by alopez7** [comment]
> El jefe de la empresa (nodo raiz del arbol) tiene que ser si o si invitado?

No. Imagina un árbol con 3 nodos (1 raíz con  2 hijos) donde los hijos tienen un monto más grande que la raíz.

**Comment by akrebs2** [comment]
Hola! Es necesario que el algoritmo sea capaz de reconstruir quiénes fueron invitados y quienes no? En el enunciado solo dice que debe retornar el valor óptimo, pero no la "solución óptima", por así decirlo

**Comment by alopez7** [comment]
> Hola! Es necesario que el algoritmo sea capaz de reconstruir quiénes fueron invitados y quienes no? En el enunciado solo dice que debe retornar el valor óptimo, pero no la "solución óptima", por así decirlo

No, no es necesario

**Comment by akrebs2** [comment]
Gracias.

Por último: en la E) es necesario que el algoritmo con tabla recorra el árbol de la manera más eficiente posible (la expuesta en C)?

A lo que voy es, uno podría recorrer al árbol de manera inconveniente, pero guardando los valores en tabla, entonces, a pesar de llamar muchas más veces de las necesarias la función para obtener un valor en específico, este se devuelve de inmediato por estar ya almacenado, me explico?

**Comment by alopez7** [comment]
No es necesario recorrer el árbol de la manera natural (esa es la versión iterativa).

**Comment by NicolasLahsen** [comment]
Podemos asumir que, si bien la cantidad de hijos es indefinida, son finitos? Me refiero a si puedo encontrar el 'maximo de hijos' que puede tener un nodo

**Comment by sjkinast** [comment]
Para la parte D y E se puede poner en la respuesta una foto o screenshot de un codigo en python ? Además, para la parte D no puedo usar el mismo algoritmo que en el E o debo implementar un algoritmo que no use una tabla obligatoriamente y que no necesariamente es con programacion dinamica?

**Comment by alopez7** [comment]
> Para la parte D y E se puede poner en la respuesta una foto o screenshot de un codigo en python ? Además, para la parte D no puedo usar el mismo algoritmo que en el E o debo implementar un algoritmo que no use una tabla obligatoriamente y que no necesariamente es con programación dinamica?

Se supone que en la parte D uses una función recursiva y en la E le agregues la tabla. Si la parte E es recursiva entonce te sirve para la D.
Puedes subir una foto mientras el archivo que subas sea en formato PDF.
