### ISSUE TITLE
Dudas I3 parte 2 pregunta 2 (dijkstra)

### ISSUE THREAD

**Issue by alopez7** [IIC2133-PUC/2019-2#116]
Acá hagan las preguntas que tengan de enunciado de la pregunta 2

**Comment by alopez7** [comment]
Subo la pregunta en PDF por si les acomoda 
[Interrogación 3 parte 2 pregunta 2.pdf](https://github.com/IIC2133-PUC/2019-2/files/3888574/Interrogacion.3.parte.2.pregunta.2.pdf)

**Comment by joaquineichholz** [comment]
Hola, para esta pregunta se espera seudocodigo o una explicación con palabras?

**Comment by alopez7** [comment]
Lo ideal es pseudocódigo porque no queda duda de los pasos. Se puede hacer con palabras mientras quede clarísimo cada paso.

No es necesario por ejemplo programar las operaciones de un heap. Pueden asumir que tienen un heap funcional.

**Comment by akrebs2** [comment]
Hola!

No se puede asumir que el grafo es acíclico, cierto?

Por otro lado, podemos ocupar cualquier algoritmo (por más ineficiente que sea) o debe mantener la complejidad de Dijkstra?

Gracias

**Comment by gnacrur** [comment]
Hola, con pseudocidigo te refieres a como el que uso el profe en clases o se busca algo más especifico que el pseudocodigo visto en clases?

**Comment by alopez7** [comment]
> Hola!
 
Hola

> No se puede asumir que el grafo es acíclico, cierto?

No

> Por otro lado, podemos ocupar cualquier algoritmo (por más ineficiente que sea) o debe mantener la complejidad de Dijkstra?

Debe tenera misma complejidad que dijkstra

> Gracias

De nada

**Comment by alopez7** [comment]
> Hola, con pseudocidigo te refieres a como el que uso el profe en clases o se busca algo más especifico que el pseudocodigo visto en clases?

No importa mientras quede claro como funciona.

**Comment by marioreinike** [comment]
Hola! La pregunta dice que se debe retornar la ruta más confiable entre 2 nodos. Es decir, hay que retornar una lista? O bien se puede retornar el último nodo de la ruta, el cual tiene como atributo a su padre (así como el algoritmo BFS)?

**Comment by alopez7** [comment]
Puedes retornar el último nodo siempre y cuando los nodos de la ruta tengan una referencia al nodo anterior

**Comment by Javierdr** [comment]
En el enunciado dice que las aristas (u,v) ∈ 𝑉. ¿No debería decir (u,v) ∈ 𝐸 ?

**Comment by alopez7** [comment]
Ups, si. Es un detallito

**Comment by lucasalamos** [comment]
Se puede entregar un codigo en python (obviamente hecho por uno mismo y que funcione) que sea de la misma complejidad de Dijkstra y sea bien distinto al visto en clases?

**Comment by alopez7** [comment]
Mientras sea en pdf..
