### ISSUE TITLE
[Tarea 3] Tests bonus

### ISSUE THREAD

**Issue by fenahurtado** [IIC2133-PUC/2019-2#117]
Hola, cuales son los tests bonus y cuales no?

**Comment by alopez7** [comment]
No lo tengo claro aún pero seremos generosos con los tests básicos y bonus.

**Comment by jvlara** [comment]
Hola, los test del repositorio deberían correr solo con una modelación correcta? me corren todos menos el 5, 8 y 9, pensé que quizás necesitan alguna heuristica o poda.

**Comment by alopez7** [comment]
Con eso deberías estar más que bien

**Comment by jfpena1** [comment]
Hola, a mi me corren los test 0, 1,2, 5 y 9. Sin embargo los demas no.
Tiene algo especial esa seleccion?
Gracias

**Comment by alopez7** [comment]
Repito, no tengo claro cuales van a ser de bonus y cuales no. No es fácil estimar la dificultad de los tests. Probablemente se determine viendo los tests que pasan las tareas en general.

**Comment by jfpena1** [comment]
gracias!

**Comment by frduran** [comment]
La tarea se testeará solo usando los 10 tests entregados? (Separando entre base y bonus) O se añadirán otros?

**Comment by alopez7** [comment]
Se usarán tests similares pero distintos
