### ISSUE TITLE
Ayuda Examen

### ISSUE THREAD

**Issue by gnacrur** [IIC2133-PUC/2019-2#118]
Hola, quería pedir ayuda en un par de cosas para facilitarnos el estudio para el examen y lograr aprender de mejor manera la materia vista en contexto de la crisis social. Agradezco que hayan mandado con tanta anticipación que materia va a entrar para el examen pero aun tengo una confusión de que parte de que clases en especifico entrará y que partes no. Además, se me hace difícil encontrar ejercicios para hacer ya que muchos ejercicios de ies mezclan materias o me cuesta saber  en cual ies anteriores buscar. Además, como no se han podido hacer muchas ayudantias tampoco hemos tenido ese recurso y por eso mismo encuentro muy bueno que el viernes haya una final. Dado esto, quería preguntarles, si es que existe la posibilidad de que se hiciera una carpeta específicamente para el examen, que nos ayude para estudiar facilitándonos el material para la prueba en un mismo lugar.  Sería muy útil si se pudiesen poner las diapositivas que debamos estudiar y quizas una selección de ejercicios a hacer de ies anteriores. Se que no estoy pidiendo poco pero creo que sería una herramienta para ayudarnos a estudiar y aprender para esta última parte del curso!

**Comment by alopez7** [comment]
Ok, lo voy a intentar. Trataré de que esté temprano en la semana.
