### ISSUE TITLE
[Tarea 3] Sleep

### ISSUE THREAD

**Issue by jptorres1** [IIC2133-PUC/2019-2#119]
¿Qué debemos hacer con los sleeps? Si bien permiten ver con mayor claridad cómo se ejecuta la tarea, estos suman más tiempo para los tests. ¿Puedo asumir que el ayudante va a sacar los sleeps al momento de correr los tests? ¿O es mejor que los borre antes de entregar mi tarea?

**Comment by alopez7** [comment]
Se deben sacar todos los sleeps
