### ISSUE TITLE
Calcular el tiempo que se demora el código

### ISSUE THREAD

**Issue by FJavierOss** [IIC2133-PUC/2019-2#12]
Hola, ¿existe algun comando en valgrind o en la terminal para saber cuanto se demora exactamente en correr el código?
De antemano gracias

Saludos

**Comment by ignaciohermosillacornejo** [comment]
Si! puedes usar `time` para probar tu código. A modo de ejemplo puedes probar:
```
time./filter <path1> <path2>
```
y ver que reporta. Fijate en el tiempo real. Al momento de ver los tiempos, no correremos tu código con `valgrind`.

Saludos

**Comment by vichoeq** [comment]
Para agregar a lo que dijo @ignaciohermosillacornejo, valgrind revisa exhaustivamente las operaciones que hace tu programa, por lo que hace que se demore mucho más.
