### ISSUE TITLE
[Tarea 3] choose_unassigned_variable

### ISSUE THREAD

**Issue by Kitaps** [IIC2133-PUC/2019-2#121]
Hola, 

tengo una duda de como podría hacer mi función para elegir la siguiente variable sin asignar. 

Hasta ahora lo que había hecho era ir una por una, 
es decir recorro una fila, una vez que llego al final parto en la siguiente fila y recorro esta, etc...

para cada celda:
reviso los vecinos
si es que hay un vecino sin asignar o del mismo distrito puedo asignar el distrito a la celda. 

Esto me trae el problema de que en los cambios de linea puedo asignar un distrito que forme una isla, ya que en la nueva linea siempre va a tener vecinos sin asignar, y de ahí en adelante todo va a estar mal. 

![image](https://user-images.githubusercontent.com/10112117/70099301-3652bf80-160d-11ea-8a12-0d707d908da6.png)

Que podría hacer? Estuve probando distintas maneras de tratar de arreglar eso, pero el problema me queda practicamente igual. 

De antemano muchas gracias.

**Comment by alopez7** [comment]
Bueno, tu deberías poder darte curnta cuando eso te lleva a algo inválido. Lo otro que podrías hacer es elegir las celdas de arriba hacia abajo pero en cada línea partes de un extremo distindo: primero paetes a la izquierda, luego a la derecha, luego a la izquierda y así.

**Comment by Kitaps** [comment]
> Bueno, tu deberías poder darte curnta cuando eso te lleva a algo inválido.

A que te refieres con eso?

>  Lo otro que podrías hacer es elegir las celdas de arriba hacia abajo pero en cada línea partes de un extremo distindo: primero paetes a la izquierda, luego a la derecha, luego a la izquierda y así.

Si, había pensado hacer eso, pero me ha costado implementarlo. Ahora se me ocurrió hacerlo agregando otra variable. Voy a probar. 

Gracias por tu respuesta

**Comment by Kitaps** [comment]
Ya, ahora esta funcionando con lo de cambiar de lado, pero no sirvió de mucho. 

Mi forma de elegir la siguiente variable a asignar está buena? Que segun yo es pesima, pero tampoco se me ocurre otra que sirva, ya que igual siempre vamos  a querar pasar por casi todas las opciones. 

O es un problema de la restricción? Creo que debe ser algo más de la resricción. 

![image](https://user-images.githubusercontent.com/10112117/70100885-022dcd80-1612-11ea-84c3-96ffa119acb5.png)

Esto de la imagen no debería pasar verdad?

**Comment by alopez7** [comment]
Esa situación no lleva a una solución. Tu debería poder programar en la función is_valid algo que se de cuenta de eso y haga inválido ese tablero. Con eso me refiero que deberías poder darte cuenta del problema.

**Comment by Kitaps** [comment]
Ahh si, tengo una función is valid. Pero se me escapa este problema...

Hasta ahora esta revisa q el distrito a asignar en la celda: 
- No haga superar el limite de personas q puede haber en un distrito
- Tenga algún vecino nulo (0) o del mismo distrito

Pero lo de los vacinos parece no ser suficiente.

**Comment by Kitaps** [comment]
Al final mi problema era la la restricción, no la función de asignación. 

Lo resolví pidiendole al codigo que si es que es un distrito nuevo (sin personas) revise si hay casillas vacías vecinas. 

Si no es nuevo que revise que haya alguna vecina del mismo distrito. 

Muchas gracias por la ayuda.
