### ISSUE TITLE
[Tarea 3] Optimizar el código

### ISSUE THREAD

**Issue by NicolasLahsen** [IIC2133-PUC/2019-2#122]
Hola! 
Actualmente mi código funciona con los primeros 3 tests, pero con los demás no termina de ejecutar. Estoy usando kcachegrind para saber donde se pierde el tiempo pero no se leerlo bien.
Estas son las llamadas de un test que corrio
![Screenshot from 2019-12-04 02-09-03](https://user-images.githubusercontent.com/42189930/70114391-1cc86c80-163b-11ea-8003-b1a198f1a008.png)

Estas son las de un test que no terminó de correr.
![Screenshot from 2019-12-04 02-12-22](https://user-images.githubusercontent.com/42189930/70114529-8d6f8900-163b-11ea-9501-c3e924ba17da.png)

¿Alguno me podría ayudar para saber donde optimizar?

**Comment by alopez7** [comment]
Hola, viendo el primer gráfico se ve que prácticamente la mitad del tiempo corresponde a las llamadas a la interfaz. Esto es bueno porque no hay ninguna parte de tu código que tome un tiempo excesivo. Viendo tu gráfico siento que tienes una distribución de tiempos ideal.
¿Cuantos tests estás logrando pasar?

**Comment by NicolasLahsen** [comment]
Hasta ahora termina de correr en 4 tests

**Comment by alopez7** [comment]
Ok, entonces puedes tratar de optimizar la forma en la que asignas las posiciones del tablero.

**Comment by NicolasLahsen** [comment]
Eso es la funcion assign? Porque es O(1) hasta ahora

**Comment by alopez7** [comment]
No, es la función que elige la posición que se asigna en esa iteración, se llama algo así como choose_variable
