### ISSUE TITLE
Tarea 3. Celda contigua

### ISSUE THREAD

**Issue by fabarros** [IIC2133-PUC/2019-2#123]
Hola! quería saber si dos celdas que están una en diagonal con la otra se consideran como contiguas :) es decir, puedo crear un distrito con puras celdas de una diagonal.
Gracias!

**Comment by Kitaps** [comment]
Parece q no

**Comment by naazocar** [comment]
En el enunciado dice que tienen que compartir una arista para ser continuas, también creo que no

**Comment by naazocar** [comment]
En el enunciado dice que tienen que compartir una arista, también creo que no
