### ISSUE TITLE
Examen

### ISSUE THREAD

**Issue by ninifdr** [IIC2133-PUC/2019-2#124]
Hola! Cuánto ponderará el examen en la nota de cátedra?
Gracias!

**Comment by alopez7** [comment]
Creo que sale en la primera clase del semestre

**Comment by ninifdr** [comment]
Ah ok gracias! Pensé que podía haber un cambio

**Comment by Gorgola22** [comment]
Hola! Quería saber donde puedo ver la ayudantía que se grabó el viernes para el examen.
Gracias de antemano

**Comment by alopez7** [comment]
Hice un aviso en el que hay un link al video

**Comment by Gorgola22** [comment]
Hola, tengo varias dudas de materia de las clases que entran para el examen:
1. En Bellman Ford es parecido a Dijkstra porque se ve la **ruta de menor costo desde un nodo hacia todos los otros**, solo que en el primero se hacen más iteraciones (por la naturaleza del problema)?
2. En *PRIM*, hay una línea de código que dice lo siguiente:
![image](https://user-images.githubusercontent.com/37182455/70569733-458bbd00-1b79-11ea-95d6-7abf79419e16.png)
Esto es así porque en cada nodo en el que se esté, se revisan los vecinos, a los que se les actualiza la clave como el valor de la arista? Entonces mi pregunta es si en cada caso, H se renueva con los nuevos vecinos, se ordena este minheap y se toma el valor de la cabeza?
3. Tengo una duda en la materia de CFC que no sé si es un error del ppt o está bien pero no sabría porqué. En la siguiente imagen coloco una arista extra que debería estar por como en el grafo original sí se conectan estas CFCs:
![image](https://user-images.githubusercontent.com/37182455/70570181-2a6d7d00-1b7a-11ea-837e-a33fa54f6693.png)
4. Me gustaría saber qué algoritmos apuntan a qué problemáticas:
![image](https://user-images.githubusercontent.com/37182455/70570318-6bfe2800-1b7a-11ea-869c-bd91c270e335.png)
a) PRIM (MST)
b) Bellman Ford y Dijkstra
c) Floyd Warshall


Muchas gracias de antemano por responder mis dudas :)
Eduardo O.

**Comment by alopez7** [comment]
Hola,

1. El algoritmo de Bellman Ford y el algoritmo de Dijkstra en código son muy distintos. Te recomiendo revisarlos en las clases. El algoritmo de Bellman Ford permite encontrar rutas más cortas en grafos con aristas negativas. Esto Dijkstra no lo puede hacer.

2. Aquí es importante el pintar el nodo. Si el nodo está pintado es porque ya salió del heap. Cuando sacas un elemento del heap revisas sus vecinos y actualizas su prioridad según las aristas que llegan al nodo pero **solo si su prioridad nueva es mejor a la anterior**. Además sabemos que las operaciones de insertar, eliminar y cambiar prioridad en un heap incluyen el reordenamiento de este.

3. Si, a ese grafo le falta esa arista, gracias por avisar.

4. Están bien los algoritmos que pusiste. También sirve Kruskal para la a)
