### ISSUE TITLE
Preguntas Examen

### ISSUE THREAD

**Issue by frduran** [IIC2133-PUC/2019-2#125]
Hola! No recuerdo si dijeron en algún momento, cuántas preguntas tendrá el examen?

**Comment by alopez7** [comment]
No puedo decirlo

**Comment by frduran** [comment]
Ok! Y respecto a la duración?

**Comment by alopez7** [comment]
No debería durar más de 3 horas. Pero la verdad no se

**Comment by frduran** [comment]
Ok gracias!
