### ISSUE TITLE
¿Al hacer floydWarshall, solo se mira la última columna de la matriz anterior o todas las columnas anteriores?

### ISSUE THREAD

**Issue by Bneya** [IIC2133-PUC/2019-2#126]
Por ejemplo, al calcular D(4) para una matriz de nodos {1, 2, 3, 4, 5}, cuando evalúo la celda 
(inicio, final) = (2, 5), cuál de estas opciones es la correcta?

1- Me quedo con el costo mínimo evaluado entre estas opciones de caminos 
- el camino 2 -> 5
- el camino  2 -> 4 -> 5

2- Me quedo con el costo mínimo evaluado entre estas otras opciones de caminos 
- el camino 2 -> 5
- el camino 2 -> 1 -> 5
- el camino 2 -> 3 -> 5 
- el camino 2 -> 4 -> 5

Muchas gracias

**Comment by alopez7** [comment]
El primero, ya que la diferencia entre D3 y D4 es que las rutas de D4 pueden pasar por el nodo 4, por lo tanto solo comparas el resultado anterior con lo que podrías construir usando el nodo 4.

**Comment by Bneya** [comment]
Entendido, gracias :)
