### ISSUE TITLE
Duda ejercicio PRIM 1 ayudantia

### ISSUE THREAD

**Issue by gnacrur** [IIC2133-PUC/2019-2#128]
Hola, tenía una duda respecto a como solucionamos esto en la ayudantía. En un momento se dijo, teniendo la lista de prioridades donde cada lista tenía una lista ligada con los nodos de esa prioridad, que si sabemos que vertice estamos buscando, entonces encontrarla dentro de la lista tomaba O(1). No entiendo porque esto tomaría O(1), ya que si tengo un máximo de w prioridades entonces puedo buscar la prioridad del nodo que estoy buscando en O(1) pero luego para buscar el nodo en la lista ligada de esa prioridad tendría que recorrerla o no?
Gracias!

PD: Pregunta aparte, para el examen, más allá de entender los algoritmos y saber aplicarlos, deberíamos sabernos de memoria todos los algoritmos que entran y ser capaz de escribirlos? o será como en la ayudantía que en el enunciado te entregan el algoritmo?

**Comment by alopez7** [comment]
Hola, los que pasa es que para el algorirltmo de prim cada nodoen el grafo puede tener una referencia directa al nodo de la lista correspondiente en la cola de prioridad. Esto hace que se no sea necesario buscar el nodo en la cola sino que se encuentra en O(1)

**Comment by alopez7** [comment]
Con respecto a tu segunda duda, no se espera que se sepan a la perfeccción los algoritmos sino que entiendan su funcionamiento y propiedades.
