### ISSUE TITLE
Resultado Bellman Ford y Floyd Warshall

### ISSUE THREAD

**Issue by ninifdr** [IIC2133-PUC/2019-2#129]
Hola! Tengo una duda conceptual.
Si Bellman Ford te da la ruta más corta desde un vértice a todos los otros y Floyd Warshall las rutas más cortas entre todos entonces si yo aplico Bellman Ford desde un nodo x, entonces las rutas mínimas hacia todos los nodos son las mismas rutas mínimas que me dan sin aplico Floyd Warshall? Osea, el grafo que me da en Bellman Ford para un nodo es subgrafo de el que obtengo en Floyd Warshall?

**Comment by alopez7** [comment]
Lo que obtenes en floyd warshall no es un subgrafo. Son las rutas más cortas entre todos los pares de nodos. Hay veces en que existen varias rutas de costo mínimo entre 2 puntos A y B por lo que no puedes asegurar que loa algoritmos retornen la misma ruta

**Comment by ninifdr** [comment]
Ah ok! Pero el costo de las rutas que obtengo en Bellman Ford tendrían que ser los mismos costos que en Floyd Warshall si analizo un nodo? Osea si hago Bellman Ford desde un nodo i y obtengo que el costo mínimo hasta j es de 4 entonces en Floyd Warshall también me daría 4? O en Floyd Warshall trato de minimizar el costo general?

**Comment by alopez7** [comment]
Si
