### ISSUE TITLE
Código sacado de Internet

### ISSUE THREAD

**Issue by fbarrientosj** [IIC2133-PUC/2019-2#13]
Quería saber si se pueden sacar extractos de código de internet (debidamente referenciados en el código). Por ejemplo, sacar algún algoritmo de ordenación.

Muchas gracias!

**Comment by vichoeq** [comment]
No hay problema, pero por que no pruebas primero implementar Insertion Sort con el algoritmo que vimos en clases?

Trata de aplicar lo que hemos visto en el curso, asi aprendes mas.

Y antes de sacar codigo de internet, considera tambien que puedes usar `qsort` de la libreria estandar de C (busca como usarla)

**Comment by Kitaps** [comment]
Yo había considerado usar los que vimos en clase, pero quicksort se supone que es más rapido...

**Comment by vichoeq** [comment]
@Kitaps Ya lo vamos a ver esta semana ;)
