### ISSUE TITLE
T4 - Duda importante

### ISSUE THREAD

**Issue by lucianoandresch** [IIC2133-PUC/2019-2#130]
Qué pasa si todos los cilindros se rebalsan? Existe flujo inverso una vez que se llega al último cilindro?
Qué sucede cuando se llega al último cilindro?

**Comment by alopez7** [comment]
Hola, si todos los cilindros se rebalsan simplemente su capacidad queda en 100 para siempre toda el egua que agregues sigue rebalsando. No se a que te refieren con flujo inverso. No se puede sacar agua si es a lo que te refieres. Piensa que pasa cuando llenas una cubeta de hielo, simplemente se rebalsa para afuera y se pierde el agua.
