### ISSUE TITLE
Conjunto de tubos

### ISSUE THREAD

**Issue by sormazabal** [IIC2133-PUC/2019-2#132]
Hola!
Dos tubos se vuelven un conjunto cuando:
1) se llena el primer tubo hasta la altura de la conexión 
o
2) se cumple (1) y además se llena el segundo tubo hasta la altura de la conexión?

Por ejemplo, si tengo dos tubos con una conexión a los 10 litros:
-Si tengo el tubo1 con 10 litros y el tubo2 con 5 litros, ¿es esto un conjunto? ¿o tienen que estar ambos tubos con 10 litros?

**Comment by alopez7** [comment]
Ambos deben estar llenos hasta la conexión
