### ISSUE TITLE
Filtrar conexiones

### ISSUE THREAD

**Issue by slecaros** [IIC2133-PUC/2019-2#133]
Hola, ¿puedo antes de partir a llenar los tubos aplicar un filtro sobre las conexiones y eliminar las que no me sirvan?

**Comment by alopez7** [comment]
Si, es muy buena idea :)

**Comment by slecaros** [comment]
ok gracias

**Comment by gtvargas** [comment]
hola @slecaros , con que no sirva te refieres a las que están a 100 o 0 cm, o hay más tipos de conexiones que no sirven?

**Comment by slecaros** [comment]
Yo me referia mas bien a revisar las rutas: si A esta conetado a B a 50 cm, pero A esta conectado a C a 10 y C a B a los 15, cuando se llegue a la conexion entre A y B los dos ya van a estar dubiendo juntos y la conexion no se va a usar (no me sirve). 

Se que en teroria esto ya se hace cuando pasan a formar parre de un mismo conjunto, pero queria saber si se pueden eliminar desde antes
