### ISSUE TITLE
T4: Conexiones a 0 cm o a 100 cm

### ISSUE THREAD

**Issue by sfga** [IIC2133-PUC/2019-2#134]
Hola,

   como dice el título, ¿pueden existir conexiones a 0 cm o a 100 cm?. Sé que en el enunciado se dice que las "conexiones están a alguna altura determinada entre 0 y 100 cm", pero quería pedirles que confirmaran si se incluyen o no los limites de este rango para las conexiones entre dos tubos.

Gracias por la atención.

**Comment by alopez7** [comment]
Si, puede existir a 0 o 100. En el caso de haber una en 0 puedes hacer que ambos tubos partan en un solo conjunto. Y en el caso de altura 100 puedes ignorar la conexión

**Comment by sfga** [comment]
Gracias por la aclaración
