### ISSUE TITLE
Outputs de prueba de los queries

### ISSUE THREAD

**Issue by sormazabal** [IIC2133-PUC/2019-2#135]
Hola!
¿De casualidad tienen los outputs que deberían darnos al ejecutar los queries (como lo que sale en el enunciado)? Es para saber si mi programa efectivamente me está dando los números correctos.
Saludos!

**Comment by alopez7** [comment]
Hola, ahora mismo no estoy con mi pc. Más tarde los subo

**Comment by sormazabal** [comment]
@alopez7 gracias! cuando puedas!
Otra cosa, importa si el resultado de un querie se imprime como un float o hay que transformarlo a int?
Por ejemplo: imprimir "40.0" en vez de "40".

**Comment by alopez7** [comment]
Si no tiene decimales da lo mismo pero es importante que muestre los decimales si tiene

**Comment by alopez7** [comment]
Hola, aquí van las soluciones de los tests de prueba. No te preocupes si no coincide el decimal exacto, al corregir se tendrá en cuenta un error por manejo de decimales.
[solution_00.txt](https://github.com/IIC2133-PUC/2019-2/files/3970247/solution_00.txt)
[solution_01.txt](https://github.com/IIC2133-PUC/2019-2/files/3970249/solution_01.txt)
[solution_02.txt](https://github.com/IIC2133-PUC/2019-2/files/3970250/solution_02.txt)
[solution_03.txt](https://github.com/IIC2133-PUC/2019-2/files/3970251/solution_03.txt)
[solution_04.txt](https://github.com/IIC2133-PUC/2019-2/files/3970252/solution_04.txt)
[solution_05.txt](https://github.com/IIC2133-PUC/2019-2/files/3970253/solution_05.txt)
[solution_06.txt](https://github.com/IIC2133-PUC/2019-2/files/3970254/solution_06.txt)
[solution_07.txt](https://github.com/IIC2133-PUC/2019-2/files/3970255/solution_07.txt)
[solution_08.txt](https://github.com/IIC2133-PUC/2019-2/files/3970256/solution_08.txt)
[solution_09.txt](https://github.com/IIC2133-PUC/2019-2/files/3970257/solution_09.txt)
[solution_10.txt](https://github.com/IIC2133-PUC/2019-2/files/3970258/solution_10.txt)

**Comment by sormazabal** [comment]
Gracias! Te pasaste!
