### ISSUE TITLE
[Tarea 4] Tiempo de ejecución

### ISSUE THREAD

**Issue by mbvanwersch** [IIC2133-PUC/2019-2#136]
Hola! Me queda una duda con el tiempo que debería tomar la tarea. En los 10 segundos máximo, se incluye la lectura del archivo test y del archivo query, o solamente el de query? 
También, se espera que en esos 10 segundos se ejecuten todas las instrucciones del archivo query?, porque por ejemplo la query 10 cuenta con 14.200 instrucciones y mi programa resuelve bien cada una pero está muy lejos de hacer todo eso en solo 10 segundos
Gracias!

**Comment by alopez7** [comment]
Tu programa debería hacer todo en 10 segundos. La pauta lo hace en menos de 1

**Comment by sormazabal** [comment]
@alopez7  me surgió una duda con lo que acabas de mencionar. El enunciado dice "Tu programa debe permitir agregar agua a los tubos y consultar los litros de agua de los tubos. Para esto se le darán comandos **por consola** con el siguiente formato:" 
Las instrucciones se darán por consola o tenemos que cargar el archivo de los queries además del de los tests?

**Comment by alopez7** [comment]
El programa se debería ejecutar como sigue:
```. /solver test.txt < queries.txt```
Este < hace que lea el archivo queries.txt como si fuera el input de la consola.
