### ISSUE TITLE
[Tarea 4]: Estructuras de datos permitidas

### ISSUE THREAD

**Issue by mafillol** [IIC2133-PUC/2019-2#137]
Hola! 

Me gustaría confirmar si está permitido el uso de las siguientes estructuras para la tarea:
- Dictionary
- List
- Tuple
- Set
- Namedtuple

Gracias de antemano.

**Comment by alopez7** [comment]
Mientras programes tu la estructura de conjuntos disjuntos no hay problema.

**Comment by mafillol** [comment]
Ok. Muchas gracias.

**Comment by ciquezada** [comment]
Esta permitida la libreria "heapq" ??

**Comment by alopez7** [comment]
]Mientras programes tu la estructura de conjuntos disjuntos no hay problema.

**Comment by Kitaps** [comment]
> Mientras programes tu la estructura de conjuntos disjuntos no hay problema.

Tiene que ser una estructura, o puede ser que el programa tenga el comportamiento de conjuntos disjuntos?

**Comment by alopez7** [comment]
Debes implementar la estructuta de datos vista en clases. Más que nada, si no la usas tu programa no va a ser tan eficiente como tiene que ser

**Comment by Kitaps** [comment]
oh ouch, ok gracias
