### ISSUE TITLE
Formato correción de tarea

### ISSUE THREAD

**Issue by stmorales** [IIC2133-PUC/2019-2#138]
Hola!

Nuestra tarea tiene que ser capaz de recibir un set de test y uno de queries para luego imprimir en consola lo que se piden en las queries? O se evaluará manualmente.

Se pide que se corra el programa de la forma python3.X main.py test_00.txt query_00.txt?
O simplemente python3.X main.py test_00.txt?

Gracias

**Comment by alopez7** [comment]
Hola, se ejecutará de la segunda forma y las queries se entregarán por consola.
El formato exacto con que se corregirá es con
```python3.x main.py test.txt < queries.txt```
El < hace que el contenido del archivo queries entre al programa por consola.

**Comment by sormazabal** [comment]
@alopez7 el output tiene que ser sólo imprimir los numeritos que dan los queries?
Por ejemplo, si imprime "Litros en tubo: 15" molesta para corregir?

**Comment by alopez7** [comment]
Si, molesta para corregir. Debe ser solo el número, tal como los archivos que subí

**Comment by jfpena1** [comment]
> Hola, se ejecutará de la segunda forma y las queries se entregarán por consola.
> El formato exacto con que se corregirá es con
> `python3.x main.py test.txt < queries.txt`
> El < hace que el contenido del archivo queries entre al programa por consola.

Hola, me imagino que en test.txt va el path de ese archivo, por ejemplo para el test 00 seria
tests/test_00.txt

Muchas gracias

**Comment by alopez7** [comment]
Si, lo mismo con queries.txt
