### ISSUE TITLE
Criterio de aprobación del ramo

### ISSUE THREAD

**Issue by cfalvarez2** [IIC2133-PUC/2019-2#139]
Hola!
Para aprobar el ramo, ¿se exigirá tener un promedio de tareas superior o igual a 4.0?

Gracias.

**Comment by alopez7** [comment]
No, solo el promedio final

**Comment by VicenteVicente** [comment]
cuál es el cálculo de la nota final?

**Comment by alopez7** [comment]
En la primera clase del curso aparece como se calcula el promedio final. Los cambios que hicimos fueron simplemente hacer que la parte de cátedra no sea reprobatoria y además como eliminamos una parte de una interrogación se promedian las 8 mejores en vez de las 10 mejores. Las ponderaciones de Ies, Examen y Tareas se quedan

**Comment by CristobalHV** [comment]
En un anuncio pasado (06-11-2019) dijeron que solo se tomarían en cuenta cuatro de las cinco mejores tareas, eso también va, no?

**Comment by alopez7** [comment]
Si, se borra la peor tarea
