### ISSUE TITLE
Error compilando - png.h no such file or directory

### ISSUE THREAD

**Issue by lucianoandresch** [IIC2133-PUC/2019-2#14]
Cloné el repositorio de la tarea, me paré en la carpeta programa e hice make, pero me sale lo siguiente: png.h no such file or directory

Cuál es la manera correcta de compilar el programa?

**Comment by haarenas** [comment]
Revisa esta issue https://github.com/IIC2133-PUC/2019-2/issues/5

**Comment by lucianoandresch** [comment]
gracias, era exactamente eso, saludos cordiales
