### ISSUE TITLE
[Tarea 4] Completitud de los tests

### ISSUE THREAD

**Issue by naoliden** [IIC2133-PUC/2019-2#140]
Hola, estaba haciendo la tarea y pasa que para 7 tests solo logro completar 99,xx % de las queries de los tests.
No se a qué se debe o si es por algún error acumulado de cálculo de decimales.
En ese caso 99% de paso del test se considera completado?

**Comment by alopez7** [comment]
Cómo estás comparando los reaultados?

Es normal que existan diferencias pequeñas de decimales. Al momento de comparar resultados consideraré un threshold en los valores al momento de compararloa

**Comment by naoliden** [comment]
Pero se va a evaluar el test completo o por queries? Porque no llego a cumplirlo al 100% pero si al 99,x% en queries...

**Comment by alopez7** [comment]
A qué te refieres con que no llegas a complirlo al 100? No te da el tiempo o la respuesta es incorrecta?

**Comment by naoliden** [comment]
de la totalidad de las queries

**Comment by alopez7** [comment]
La verdad no lo he decidido aún, guardaré los datos de correctitud en la planilla final y veré si es necesario dejar un threshold de correctitud

**Comment by naoliden** [comment]
propongo corre/no corre :)

**Comment by Tito0906** [comment]
Hola!  @alopez7 tenía la misma duda que se plantea en esta issue. Mi programa entrega los resultados con algunos decimales diferentes (probablemente porque hago varias divisiónes para el calculo del agua). Quería saber cuán grave era las diferencias, como por ejemplo, las que se ven en la foto a continuación. 
![image](https://user-images.githubusercontent.com/42530158/71311102-0f60ff80-23fb-11ea-96d8-e826e01c4360.png)
De ser importantes, que recomendación nos darían para evitar esto?

**Comment by alopez7** [comment]
Tal como dije antes
> Es normal que existan diferencias pequeñas de decimales. Al momento de comparar resultados consideraré un threshold en los valores al momento de compararlos

**Comment by Calomi** [comment]
@Tito0906, @naoliden, contra que están comparando sus resultados? como saben que con lo que están comparando está correcto?

**Comment by Tito0906** [comment]
@Calomi En esta issue preguntaron por los outputs y los dieron: [https://github.com/IIC2133-PUC/2019-2/issues/135](url) . Para comparar hay varias maneras de hacerlo, en mi caso sólo usé la herramienta de vscode.
