### ISSUE TITLE
Problema de formato para leer los inputs 

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2133-PUC/2019-2#141]
Hola, tengo linux y estoy con problemas para correr las queries, no reconoce los números como string, produciendo un syntax error 

![image](https://user-images.githubusercontent.com/26394381/71310685-c3f82280-23f5-11ea-98c3-c0585fe1dc53.png)

Feliz si me pueden ayudar que no he podido solucionarlo :) 
Gracias

**Comment by alopez7** [comment]
Eso está raro. ¿Cómo estás llamando a tu programa? Parece como que estás importando el archivo de queries.

**Comment by joaquineichholz** [comment]
Como dijeron que lo hiciéramos.. python main.py "tests/test_01.txt"  < "queries/query_01.txt"

Es algo de mi computador, le mande mi código a un amigo y haciendo lo mismo que yo le corre sin problemas, si le agrego comillas a las consultas funciona, por ejemplo "f 2 2 200" no tiene problemas

**Comment by ifcarrera** [comment]
Seguro que estás usando python3?

**Comment by joaquineichholz** [comment]
si seguro, me cambie a windows para trabajar y todo ok!

Gracias
