### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Kitaps** [IIC2133-PUC/2019-2#142]
Hola, 

hay alguna manera de poder ver si los resultados al correr las quesrys están bien?

Que he estado testeando manualmente, y hasta ahora todo se ve bien.
Y cuando corro todas las querys de una no me tira error.

Pero no se si el resutado es correcto. 

Hay alguna manera de comparar?

Gracias

**Comment by alopez7** [comment]
Puedes escribir un pequeño script de python que compare los resultados. Es importante que tenga un threshold asociado por ejemplo hasta 0.001 de diferencia

**Comment by Kitaps** [comment]
Dale, gracias!!

**Comment by Bneya** [comment]
> Puedes escribir un pequeño script de python que compare los resultados. Es importante que tenga un threshold asociado por ejemplo hasta 0.001 de diferencia

Hola, cuando te refieres a hacer un script para comparar resultados, contra qué tengo que compararlos? Creo que no entiendo bien el formato de los archivos de queries, se encuentran ahí los resultados que mi programa debería entregar?

Muchas gracias :)

**Comment by alopez7** [comment]
Es que en esta [Issue ](https://github.com/IIC2133-PUC/2019-2/issues/135)subí los outputs de los tests

**Comment by Bneya** [comment]
Gracias
