### ISSUE TITLE
¿Calculo de mediana para N pixeles o 9?

### ISSUE THREAD

**Issue by lucianoandresch** [IIC2133-PUC/2019-2#15]
Para la tarea tenemos que realizar una función que calcule la mediana. ¿Para hacerlo basta con que dicha función acepte 9 valores? Esto sería debido a que cada pixel está rodeado por 9 pixeles.

¿O es necesario hacer una función mediana que acepte N elementos, lo cual sería mucho más complicado?
A mí me gustaria optar por la primera opción, debido a que es más simple, pero me gustaría escuchar la opinión de alguien más acerca de si es mejor la segunda opción.

Gracias de antemano y saludos cordiales.

**Comment by ignaciohermosillacornejo** [comment]
Basta con hacerla para los 9 pixeles.

Saludos
