### ISSUE TITLE
Funciones propias en imagelib

### ISSUE THREAD

**Issue by JorgeBdelaT** [IIC2133-PUC/2019-2#17]
Hola, podemos crear funciones propias dentro de la librería imagelib? En particular me gustaría  crear una para inicializar una imagen vacia. Saludos!

**Comment by ignaciohermosillacornejo** [comment]
Hola Jorge,

No puedes modificar el código de Imagelib, sin embargo dentro de la carpeta filter puedes hacer todo lo que quieras (crear nuevos archivos, más funciones etc).

La razón de esto es que si tu código depende de modificaciones en en Imagelib no va a funcionar con el auto corrector.

También eres libre de usar todas las estructuras definidas en Imagelib.h y estudiar el código de Imagelib.c para tu solución.

Saludos
