### ISSUE TITLE
Archivos a subir & no subir

### ISSUE THREAD

**Issue by jfpena1** [IIC2133-PUC/2019-2#18]
Hola quería saber si para subir los códigos a github es necesario ignorar algun archivo en particular con un .gitignore. Por ejemplo, las fotos output que hemos generado para probar nuestro algoritmo.

Respecto a otro tema, podemos guardar otros archivos dentro de la carpeta filter, como por ejemplo el archivo matrix.c del taller 0 de C? Hasta ahora lo tengo guardado ahí para facilitar su llamado en el main (hago include de esta "libreria").

Muchas gracias.

**Comment by arbiocanpion** [comment]
Sumandome a la issue de @jfpena1, tengo la duda de si esta permitido subir otra carpeta dentro de la carpeta src en el github personal de la T00.

¡Desde ya muchas gracias!

**Comment by ignaciohermosillacornejo** [comment]
Hola! 

Se espera que ustedes trabajen dentro de la carpeta _filter_. Cualquier cosa que hagan fuera de la carpeta _filter_ puede que intefiera en el *juez* y se caiga su proceso de correción. 

Dentro de la carpeta _filter_ son libre de hacer lo que quieran como nuevas carpetas, archivos, includes, etc.

No es necesario borrar nada, el juez automáticamente borra todo y vuelve a compilar su código para el servidor donde corre. Tampoco es necesario que borren las imágenes. 

Resumiendo, para que su código se corriga bien tienen que seguir dos reglas:

1. Solo trabajar dentro de la carpeta que les indicamos (en este caso _filter_)
2. No modificar los otros archivos (pueden verlos y estudiarlos) ya que si su código depende de algúna modificación a ellos, no va a funcionar.

Saludos

**Comment by Arcoirisky** [comment]
Subir las imagenes de prueba en /Programa estarìa mal? D:
La idea es que todo estè compilado no?

pd: Sorry por los ` pero que mis tildes se revelaron u-u

**Comment by alopez7** [comment]
No importa si cambias las imágenes de carpeta porque no se va a corregir con esas imágenes. Lo que importa es que tu programa compile con make y se ejecute con el comando descrito en en enunciado.

**Comment by Arcoirisky** [comment]
Perfect
