### ISSUE TITLE
¿A qué pixeles aplico el filtro de mediana?

### ISSUE THREAD

**Issue by lucianoandresch** [IIC2133-PUC/2019-2#19]
Tengo 2 dudas, por favor me las podrían aclarar?

1)¿El filtro de mediana se aplica a TODOS los pixeles o solo a los que están "malos"? Si es lo segundo, cómo sé si un pixel está malo? Escuché que los blancos estaban malos, pero puede haber una imagen de la luna que tenga pixeles blancos y estén buenos.

2)¿Al aplicar el filtro de mediana voy creando una nueva imagen? Esto es debido a que si aplico el filtro de mediana en la misma imagen eso alterará las medianas de los siguientes pixeles. 

Saludos cordiales y gracias de antemano.

**Comment by Jaluco** [comment]
Creo que en el enunciado aparece que para calcular la mediana se ocupan los pixeles de la imagen original, osea que no deberias considerar los alterados en el filtro

**Comment by alopez7** [comment]
Debes aplicar el foltro usando solo pixelds viejos para la mediana. El filtro se hace para cada pixel de la imagen

**Comment by Jaluco** [comment]
Para cada pixel? En el enunciado sale para cada pixel faltante

**Comment by Kitaps** [comment]
>El filtro se hace para cada pixel de la imagen

Pero eso no haría q toda la imagen quede borrosa?

**Comment by fabarros** [comment]
> Para cada pixel? En el enunciado sale para cada pixel faltante

same duda.

**Comment by alopez7** [comment]
El fitro se hace a cada pixel de la imagen. Esto puede hacer que la imagen se vea más borrosa pero elimina mejor el ruido.
