### ISSUE TITLE
Casting de Malloc

### ISSUE THREAD

**Issue by fabarros** [IIC2133-PUC/2019-2#2]
Hola! hoy en la ayudantía nos mostraron cómo usar el HEAP de memoria con un ejemplo como el siguiente:
`int* b = malloc(sizeof(int) * 3)`
Sin embargo, estaba leyendo la guía de punteros del repositorio y ahí dice que cada vez que se pide memoria con malloc hay que hacer casting e indicar a qué tipo de variable apunta el puntero (int para el caso mostrado en la guía). Escriben algo así:
`int *puntero;`
`puntero = (int *)malloc(sizeof(int) * 3)`
Mi pregunta es, cuánto tengo que castear el puntero que me entrega malloc? Por qué en la ayudantía no lo hicieron?
Saludos!

**Comment by alopez7** [comment]
Hola, en las versiones más antiguas de C era necesario transformar el puntero retornado por malloc al tipo correspondiente pero eso ya no es necesario hacerlo en las versiones más modernas.

**Comment by fabarros** [comment]
Fino, gracias!
