### ISSUE TITLE
[Tarea 0][Analisis] Duda complejidad

### ISSUE THREAD

**Issue by Jaluco** [IIC2133-PUC/2019-2#20]
¿Es necesario que consideremos en nuestro calculo de la complejidad las funciones dadas en imagelib?

**Comment by alopez7** [comment]
No, solo deben considerar para el cálculo lo que hace su algoritmo

**Comment by gatochico** [comment]
Hola! No se si entendí bien, entonces es sólo analizar la complejidad del cálculo de la mediana para n pixeles?

**Comment by alopez7** [comment]
Si
