### ISSUE TITLE
Informe, especificaciones

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2019-2#21]
Hola!!

¿Existe alguna extensiòn màxima/minima en el informe? ¿Què es lo que se espera en nivel de detalle?

**Comment by ignaciohermosillacornejo** [comment]
Hola! no hay extensión máxima y mínima, pero lo que les pedimos para este informe es super sencillo, no es más que un análisis básico de su algorítmo y un gráfico. No creo que necesites más de una plana.
