### ISSUE TITLE
¿Qué esquina es la 0,0?

### ISSUE THREAD

**Issue by lucianoandresch** [IIC2133-PUC/2019-2#22]
Hola.

Quisiera preguntar qué esquina de la imagen es la (0,0)?
En otras palabras, cuál es la esquina con row=0 y col =0?

Es la superior izquierda?
Cómo van creciendo los pixeles? hacia la derecha? hacia arriba? Me podrían orientar con una imagen por favor, muchas gracias,

Saludos cordiales.

**Comment by lucianoandresch** [comment]
por otro lado, cómo creo una imagen nueva de NxM pixeles?

**Comment by ignaciohermosillacornejo** [comment]
HHola @lucianoandresch 

El pixel (0,0) es el de la esquina superior izquierda. Crecen las filas hacia abajo y las columnas hacia la derecha. Te adjunto una imágen tambien mostrando esto.

![image](http://opensask.ca/_images/image_pixels.png)

**Comment by alopez7** [comment]
Puedes crear una nueva matriz con valores para los 3 canales de los pixeles y luego remplazas esos valores en la imagen inicial. Finalmente liberas la matriz creada.
