### ISSUE TITLE
Duda Fechas

### ISSUE THREAD

**Issue by gnacrur** [IIC2133-PUC/2019-2#24]
Hola, quería saber donde puedo revisar las fechas. No logre encontrar el programa. En particular me interesa saber las fechas de las tareas. Gracias.

**Comment by alopez7** [comment]
Hola, no tenemos las fechas concretas de las tareas ya que va de la mano con la materia que se esta viendo. Te puedo dar los temas:
T0: Introducción a C
T1: Árboles
T2: Backtracking
T3: Hashing y búsqueda
T4: Grafos

Es posible que la tarea 23 y cambien de orden
