### ISSUE TITLE
Problema con still reachable leaks

### ISSUE THREAD

**Issue by gnacrur** [IIC2133-PUC/2019-2#26]
Hola, estaba viendo con valgrind si tengo errores o leaks. Por lo poco que entendí de lo que me retorna valgrind, no tengo problemas más que un  reachable leak de 800 bytes. Busque en internet y la gente dice que no es realmente un leak y que no afecta en nada, pero en realidad no se si en esta evaluación se considera lo mismo. No se porque se genera el leak ya que estoy liberando todo lo que use (que es solo la función para recibir el input de la imagen). 
![image](https://user-images.githubusercontent.com/42191903/63539611-8091b400-c4e8-11e9-8db3-5acecf42f434.png)
Aprecio cualquier ayuda!

**Comment by pdesolminihac** [comment]
Hola!
`still reachable leaks` se refiere a bloques de memoria que fueron asignados que podrían haber sido liberados pero no lo fueron. Esto se puede ver dentro del Heap Summary en donde dice:
`total heap usage: 26 allocs, 2 frees, 1,885 bytes allocated`
Es decir, en tu programa asignaste memoria del Heap a 26 bloques (utilizando `malloc` ó `calloc`) pero solo liberaste 2 de ellos. Te recomiendo revisar tu código en las partes donde realizaste las asignaciones para liberar todo correctamente.
Este tipo de leaks siguen contanto como memory leaks en esta instancia, ya que es memoria que sigue asignada y nunca fue liberada.
Espero que te esto te sirva!

**Comment by gnacrur** [comment]
El problema es que nunca uso malloc ni calloc y además, destruyo las instancias de imágenes creadas. ¿Hay alguna otra posibilidad?

**Comment by pdesolminihac** [comment]
¿No le hiciste ningún cambio al archivo `imagelib.c`?

**Comment by gnacrur** [comment]
No, ninguno. Yo también lo encuentro bastante raro. ¿Hay alguna instancia en la que le pueda mostrar mi código a algún ayudante para ver si identifica el problema? Realmente me gustaría entender que esta pasando.

**Comment by vichoeq** [comment]
Hola, ¿en qué sistema operativo estás corriendo valgrind? Encuentro muy raro el mensaje que dice "error calling PR_SET_TRACER ..."

Lo otro, al final de valgrind dice "para ver el detalle de los leaks, ejecuta el programa con los flags `--leak-check=full` y `--show-leak-kinds=all` "

¿Probaste con el segundo flag?

**Comment by gnacrur** [comment]
Hola, estoy usando windows 10 pro. Si probé, pero no entendí mucho de lo que salía:
![image](https://user-images.githubusercontent.com/42191903/63608863-edb64f80-c5a3-11e9-9af1-f597c5fe9d31.png)
![image](https://user-images.githubusercontent.com/42191903/63608916-0b83b480-c5a4-11e9-8962-fd71337b7607.png)

**Comment by alopez7** [comment]
Estás ejecutando valgrind con el main.c pero debes hacerlo con el ejecutable de tu programa

**Comment by vichoeq** [comment]
Parece tener que ver con ese error raro que aparece al principio. 

Haz `make clean` y vuelve a hacer `make`.

¿Aparece algún error o warning en la compilación?

**Comment by vichoeq** [comment]
@alopez7 detallazo.

**Comment by vichoeq** [comment]
@alopez7 tu programa no se llama main.c

Deberia llamarse `filter`

**Comment by gnacrur** [comment]
Muchas gracias, todo funcionando bien. Error humano, al parecer partí con C más perdido de lo que esperaba.
