### ISSUE TITLE
Recorrer un Struct

### ISSUE THREAD

**Issue by fabarros** [IIC2133-PUC/2019-2#28]
Hola! He estado medio complicado con la Tarea, ya resolví algunas cosas pero aun no cacho cómo recorrer las variables dentro de un Struct.
Si me pudieran orientar un poco sería bacán :D.
Gracias y saludos!

**Comment by vichoeq** [comment]
En el material "Taller 0 - Intro a C", la parte "7 - Structs" tiene archivos donde se explica como definir y utilizar un structs. En el main puedes encontrar explicacion general de como funcionan.
