### ISSUE TITLE
Informe t0

### ISSUE THREAD

**Issue by francisca1** [IIC2133-PUC/2019-2#29]
buenas! quería saber que tipo de análisis se espera en la parte 2 del informe, ya que no me quedó muy claro que es lo que se espera que escribamos.
Gracias!

**Comment by alopez7** [comment]
Hola, a partir de los datos de tiempo obtenidos al ejecutar tu programa con los tests deberías poder determinar empíricamente cual es la complejidad del algoritmo. Además puedes discutir cómo se relaciona la complejidad obtenida empíricamente con la complejidad teórica

**Comment by gnacrur** [comment]
@alopez7 Hola, respecto a la determinación de la complejidad empírica, la idea es que calculemos cuanto toma cada operación y calcular la complejidad en cantidad de operaciones de cierto tipo?

**Comment by alopez7** [comment]
Si, en este caso deberías contar todas las operaciones del loop principal de tu programa. Con el loop principal de tu programa me refiero cuando iteras sobre los pixeles de la imagen.
