### ISSUE TITLE
Paquetes Atom

### ISSUE THREAD

**Issue by Kitaps** [IIC2133-PUC/2019-2#3]
Hola, 

quería saber que paquetes de Atom recominedan(usan ustedes) para trabajar con C ?

Gracias

**Comment by alopez7** [comment]
Hola,
te puede servir lo que hablé en esta [issue](https://github.com/IIC2133-PUC/2019-2/issues/1).

**Comment by Kitaps** [comment]
Ahh heavy, no caxaba la relación entre Linter y Atom jajaj
Gracias
