### ISSUE TITLE
Tarea ejemplo

### ISSUE THREAD

**Issue by Tngarrido** [IIC2133-PUC/2019-2#30]
Hola, sufrí un inconveniente con mi notebook oficial, por lo que me encuentro  trabajando en otro con SO ubuntu, en el cual no me manejo mucho,  realice la compilación,  pero al momento de probar el codigo de modo ejemplo me tira un error que según [aca](https://es.stackoverflow.com/questions/383/qu%C3%A9-significa-violacion-de-segmento) esta asociado a problemas con permisos de accesos de memoria. ayuda, dejo como estoy ejecutando el programa 
![Captura de pantalla de 2019-08-24 15-11-03](https://user-images.githubusercontent.com/42189869/63641738-6a6b2b80-c681-11e9-876a-c07cb2d5e4a8.png)

**Comment by Pipelao** [comment]
Hola @Tngarrido 

Primero debes correo `make` dentro del directorio `Escritorio/estructura/T0-2019-2-Tngarrido/Programa,` y luego ejecutar `./filter ./tests/test_00.png ./output/output_00.png`. En comparación con lo que tú colocas es que la carpeta es *tests* y no *test*, también como recomendación asegurate que tengas creada la carpeta output, no estoy seguro que el programa pueda crear un directorio (carpeta).

PD: no soy ayudante.

**Comment by Tngarrido** [comment]
Gracias @Pipelao , me resulto.
