### ISSUE TITLE
Unidad de tiempo entregada por "time"

### ISSUE THREAD

**Issue by sormazabal** [IIC2133-PUC/2019-2#32]
Hola!
Al usar ` time ./filter tests/test_0$i.png tests/intentos/test_0$i.png` (gracias issue #23 !) la consola entrega distintos tiempos de demora para el filtro. Tengo la duda de si lo entrega en segundos o milisegundos. Por ejemplo:

`Time 0

real    0m0.159s
user    0m0.146s
sys    0m0.013s
`

Sé que parece una duda muy trivial, pero es para escribir bien el informe.

**Comment by alopez7** [comment]
El tiempo real el lo que finalmente te interesa a ti. El tiempo sys es el tiempo usado en llamadas al sistema operativo desde tu programa como cuando haces malloc o free. El tiempo user es todo el tiempo usado por solo código de tu programa (real - sys).
