### ISSUE TITLE
Duda uso memoria adicional merge sort

### ISSUE THREAD

**Issue by francisca1** [IIC2133-PUC/2019-2#33]
Hola! estaba repasando la ayudantía y me quedó una duda con la memoria adicional ocupada por mergesort, para esto se ocupa una formula parecida a la de complejidad en algoritmos recursivos, en la formula, se pone que M(n) = n + M(n/2).
![imagen](https://user-images.githubusercontent.com/26394880/63655684-53980800-c759-11e9-8178-9c47a1120b9a.png)
pero dentro de la llamada recursiva de mergesort se piden 2 arreglos de n/2, debería ser M(n) = n + 2*M(n/2)?.
Gracias.

**Comment by alopez7** [comment]
Hola, la memoria usada por los arreglos A1 y A2 es n/2 cada uno por lo tanto aparece el término n en la recurrencia.
El M(n/2) aparece porque es la mempria usada al llamar recursivamente el método mergesort. Si bien se hacen 2 llamadas recursivas, se hace solo una a la vez por lo que no sumamos la memoria usada por ambas llamadas recursivas sinó que solo una.
Esta simplificación la podemos hacer porque al analizar uso de memoria solo nos interesa la memoria máxima que puede necesitar el algoritmo al ejecutarse (mácima memoria en uso en cualquier instante del algoritmo). 

Espero esto responda tu pregunta
