### ISSUE TITLE
Sobre el error de Valgrind "PR_SET_PTRACER"

### ISSUE THREAD

**Issue by felipegarcia98** [IIC2133-PUC/2019-2#37]
Quería preguntar si alguien tiene alguna idea-conocimiento sobre este error, si se evaluara y/o la importancia que podría tener en el futuro

PD: Tengo Windows 10

**Comment by ignaciohermosillacornejo** [comment]
Hola! 

Esto te dice que tienes un error manejando la memoria en tu código, probablemente accediendo un objeto pensando que es un puntero o viceversa. 

Saludos
