### ISSUE TITLE
Correr código en Mac hecho en Ubuntu

### ISSUE THREAD

**Issue by naazocar** [IIC2133-PUC/2019-2#38]
Hola!

Sucede que hice mi tarea en ubuntu 16.04, la corrí con valgrind y la revisé con Diff. No tuve ningún problema con valgrind y con Diff me aseguré de que las imágenes quedan igual a la pauta.

El problema es que luego de subir el código a git, quise probarlo desde un macbook pro y luego de compilar, al intentar correr el programa me sale el error que puse en el título.

Quería saber a qué se puede deber esto y si influirá en mi nota o no (considerando que en ubuntu corre como debería).

Gracias de antemano :)

**Comment by ignaciohermosillacornejo** [comment]
Hola!
Esto puede pasar por varias razones:
1. Estas intentando ejecutar en MacOS archivos binarios compilados para Ubuntu. Para solucionar esto tienes que borrar los binarios y volver a compilar. Debes hacer esto cada vez que cambias de sistema operativo.
2. No tienes permisos para compilar. Tienes que marcar el archivo como ejecutable, para eso prueba correr este comando ```chmod +x ./filter```

Saludos
