### ISSUE TITLE
Error al instalar Ubuntu en VirtualBox

### ISSUE THREAD

**Issue by ncasassus** [IIC2133-PUC/2019-2#4]
Estaba tratando de instalar Ubuntu en la maquina virtual, siguiendo los pasos del link que nos recomendaron usar (https://es.wikihow.com/instalar-Ubuntu-en-VirtualBox). Y en el paso 3.1 en la parte de instalar Ubuntu en VirtualBox me aparece este error de Kernel. Qué debo hacer?

![Screen Shot 2019-08-09 at 13 51 51](https://user-images.githubusercontent.com/37166054/62799039-bfb61300-baad-11e9-90a2-4982bac4326d.png)

**Comment by alopez7** [comment]
Hola,
No se por que se produjo tu error pero te recomiendo probar lo siguiente:

* Busca el error en google por si alguien tuvo el mismo problema
* Trata de hacer denuevo la máquina virtual en virtualbox
* Descarga otra imagen de ubuntu u otra versión e intenta denuevo

Si nada funciona te puedo tratar de ayudar en persona. Avísame cualquier cosa. Si lo logras solucionar por favor avisa cómo lo hiciste por si alguien más tiene el mismo problema.
Saludos
