### ISSUE TITLE
"Segmentation fault" al probar la T1 con naive_search

### ISSUE THREAD

**Issue by sormazabal** [IIC2133-PUC/2019-2#45]
Cuando trato de probar main.c usando el naive_search que viene de ejemplo obtengo el error: "Segmentation fault (core dumped)". Lo estoy probando con `./decode test_00.png test_00.txt output_00.txt`, ya que dice que uno lo tiene que probar usando `./decode <input_image.png> <queries.txt> <output.txt>`. ¿Lo estoy probando mal?

**Comment by alopez7** [comment]
Si descomprimes los archivos y los dejas directamente en el mismo directorio que la makefile debería funcionar pero si tienes los tests en una carpeta por ejemplo llamada tests debes hacerlo así:

```sh
./decode tests/test_00.png tests/test_00.txt output_00.txt
```
Esto dejaría el output en el directorio de la makefile.

A priori no puedo saber cual es tu error ya que segmentation fault puede ser muchas cosas. Si crees que es el path de los archivos es incorrecto puedes hacer lo siguiente:

```C
FILE* words_file = fopen(argv[2], "r");
FILE* output_file = fopen(argv[3], "w");

if (!words_file || !output_file)
{
     printf("ERROR: algun path esta mal\n")
     return 0;
}
```

Esto funciona porque cuando un archivo no se abre correctamente la función fopen retorna 0.

**Comment by alopez7** [comment]
Si no ese el error ejecuta el código con valgrind y mándame el output por aca.

**Comment by sormazabal** [comment]
Había que probarlo con `./decode tests/test_00.png tests/test_00.txt output_00.txt`. Muchas gracias!! :D :D
