### ISSUE TITLE
Fecha entrega T1

### ISSUE THREAD

**Issue by R0W5tortion** [IIC2133-PUC/2019-2#47]
En el enunciado dice que la tarea se entrega el 17 de agosto. O realmente vamos a tener un año para entregarla, o bien se espera que usemos maquinas del tiempo para volver atras unas semanas, o (lo mas probable pero fome) simplemente es un error. 

¿Seria correcto asumir que la entrega es el 17 de septiembre (de 2019 d.c. por supuesto)?

**Comment by ignaciohermosillacornejo** [comment]
Hola @R0W5tortion!

La tarea se entrega el 17 de septiembre, gracias por darte cuenta del error! 

Saludos
Ignacio

**Comment by alopez7** [comment]
Ups, lo corrijo en un aviso
