### ISSUE TITLE
Múltiples Repositorios de Tarea 1

### ISSUE THREAD

**Issue by felipegarcia98** [IIC2133-PUC/2019-2#48]
Buenas, quería saber cuál repositorio usar, ya que al aceptar la invitación se me crearon 2 repositorios desde ayudantes distintos:
-> alopez7 -> T1-2019-2-felipegarcia98-1
-> vichoeq -> T1-2019-2-felipegarcia98

**Comment by alopez7** [comment]
Usa el que no tiene -1 al final

**Comment by Pipelao** [comment]
Hola @alopez7 , 

Con respecto a los repositorios con número al final, en el enunciado de la tarea dice que hay que borrarlos, ¿cómo se borran?, no logré hacerlo.

Gracias de ante mano.

**Comment by felipegarcia98** [comment]
@Pipelao el repositorio, en github, tiene una pestaña "Settings". Al final de ésta se encuentra la opción de eliminar, en la "Danger Zone"

**Comment by Pipelao** [comment]
@felipegarcia98 Gracias.
