### ISSUE TITLE
Suffix Trie completo o parcial?

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2133-PUC/2019-2#49]
Hola, debemos hacer un Suffix Trie completo, con todos los sufijos o solo hacer un "Suffix Trie" con todas las palabras que son sufijos entre si? con la primera opción abrían ramas redundantes, ya que hay sufijos que no nos interesan revisar porque no llegan a palabras de las que queremos contar... 

por ejemplo si quiero contar las palabras : 0 1 0 y 1 0, debería hacer un árbol con 2 ramas, es decir 
 
1 - 0
0 - 1 - 0

o debería agregar todos los sufijos que se puedan para tener un Suffix Trie?, las ramas del árbol serian las siguientes: 

0
1 - 0
0 - 1  - 0

Gracias!
Joaquín

**Comment by alopez7** [comment]
La idea es que la estructura no dependa de las palabras a buscar. Ingresa todos los sufijos de cada vertical, horizontal y diagonal.

**Comment by joaquineichholz** [comment]
Eso depende de como.se vea el problema o no? yo resolvi el problema haciendo que no dependa de la sopa, por lo que hice un suffix trie con las palabras a buscar y luego recorro la sopa letra por letra hasta salir del arbol, cuando esto ocurre avanzo a la siguie letra... esto me ahorra muchas iteraciones innecesarias en la sopa 

Esta bien esta manera de ver el problema? Al final,  priorice buscar un grupo de palabras en cualquier sopa versus buscar cualquier grupo de palabra en una sopa...

**Comment by vichoeq** [comment]
Tu solución está perfecto; vas a encontrar que palabras existen en la sopa si buscas los **sufijos** de la sopa en el **Trie** de la lista de palabras a buscar. 

Se propuso que hicieran un **Suffix Trie** de la sopa ya que idealmente la cantidad de palabras a buscar iba a ser inmensa en comparación con la sopa, pero eso resultó poco práctico en términos de tamaño de archivos, por lo que la achicamos.

Ahora bien, no olvides que debes contar cuantas veces aparece cada palabra, así que asegurate de incluir esto en tu código.

**Comment by vichoeq** [comment]
Como nota al pie, no hay problema con hacer algo distinto a lo que se sugiere en el enunciado mientras funcione y no sea más lento.
