### ISSUE TITLE
Problema con malloc tarea 1

### ISSUE THREAD

**Issue by jpjoublan** [IIC2133-PUC/2019-2#50]
Hola! 

Tengo un problema en la tarea 1, cuando corro mi código con el primer test, el más chico, me funciona bien y me da el output correcto, pero al momento de intentar correrlo con otro de los tests, que son más grandes, me tira el siguiente error:

`decode(27472,0x115ae15c0) malloc: can't allocate region
*** mach_vm_map(size=18446744056529682432) failed (error code=3)
decode(27472,0x115ae15c0) malloc: *** set a breakpoint in malloc_error_break to debug
Segmentation fault: 11`

He buscado y no entiendo a que se debe el error, más allá de saber a que es un error de memoria, creo que está asociado al editor, estoy usando Atom.

**Comment by alopez7** [comment]
Me da la impresión de que te estás quedando sin memoria. Revisa al hacer malloc si el puntero retornado es igual a NULL. Luego ejecuta el programa con valgrind y ve cuanta memoria está alocando tu programa. Esta es una tarea de alto consumo de memoria por lo que es necesario optimizar en ese sentido. Puedes tratar de usar tipos que usen menos memoria, por ejemplo puedes usar uint8_t en vez de int para los 1s y 0s.
Por otro lado, donde estás ejecutando tu programa? una máquina vitual? Si es así, cuanta memoria ram le asignaste a la máquina virtual?

**Comment by vichoeq** [comment]
Si te estas quedando sin memoria, prueba usando la solución que propuso tu compañero en #49 , ocupa menos memoria.
