### ISSUE TITLE
[Materia] Duda Θ(2^h)

### ISSUE THREAD

**Issue by NicolasLahsen** [IIC2133-PUC/2019-2#55]
No me queda claro por qué 2<sup>h</sup> podría acotar por abajo a _F(h)_. Me hace mas sentido usar el operador Ω en vez de Θ en este caso.

![Screenshot from 2019-09-10 16-58-08](https://user-images.githubusercontent.com/42189930/64646166-e3da7c00-d3ec-11e9-9884-0918dcf3eeb4.png)

**Comment by alopez7** [comment]
F(h) in Θ(2<sup>h</sup>) implica que F(h) in O(2<sup>h</sup>) y F(h) in Ω(2<sup>h</sup>).

De la expresión F(h) <= phi<sup>h</sup>/sqrt(5) aparece directamente que F(h) in O(2<sup>h</sup>).

Para demostrar que F(h) in Ω(2<sup>h</sup>) hay que hacer lo siguiente:
F(h) >= phi<sup>h</sup>/sqrt(5) + 1 (se quita el piso de la expresión sumando 1)
Por lo tanto F(h) in Ω(2<sup>h</sup>)

**Comment by NicolasLahsen** [comment]
Buenisimo, muchas gracias!!
