### ISSUE TITLE
Naive Search

### ISSUE THREAD

**Issue by lucianoandresch** [IIC2133-PUC/2019-2#56]
No entiendo lo que hace el naive search. Como que corro el programa y el output me da que son puros ceros.

Cómo puedo testear mi programa verificando que me de el output correcto si en los archivos de la carpeta test no están los archivos output? 

Gracias

**Comment by alopez7** [comment]
Hola, son casi puros ceros pero hay en todoa los tests algunas palabras. Fíjate bien en los archivos de output.
