### ISSUE TITLE
Ayuda con errores de memoria Valgrind (variable no inicializada)

### ISSUE THREAD

**Issue by gnacrur** [IIC2133-PUC/2019-2#57]
Hola, estoy teniendo problemas de memoria ya que mi función de agregar sufijos a mi trie se queja de que : `Conditional jump or move depends on uninitialised value`. Usando` --track-origins=yes` me di cuenta que el problema se originaba cuando yo inicializaba mi trie: `Trie* trie = trie_init();` 
Quería saber si alguien se había topado con un problema así al inicializar un struct o si alguien se le ocurre como podría averiguar cual es el problema o solucionarlo. Gracias!

**Comment by alopez7** [comment]
Cuando inicializas una estructura asegúrate de darle valores a todos sus atributos ya que si lees alguno de ellos te va a salir ese error.

**Comment by gnacrur** [comment]
Con lo que me dijiste logré identificar el problema! Pero no logro solucionarlo. Lo que pasa es que mi trie tiene un atributo left y right que al hacer init parten como nulos. Por lo tanto, les entrego NULL en el init. Creo que por eso valgrind se queja, porque parten nulos. El problema es que necesito que partan nulos porque solo tienen left y right si es que el trie tiene rama 0 y rama 1. ¿Existe alguna forma de modelar sin tener problemas de memoria?

**Comment by ignaciohermosillacornejo** [comment]
Lo que estás haciendo es correcto de setear los atributos left y right como null por lo que tu error debe estar en otro lado probablemente.

**Comment by gnacrur** [comment]
Otro antecedente es que solo me dice que hay errores en el primer llamado a la función que usa el Trie. Más adelante en el código se vuelve a usar esta función pero no se reportan problemas. Mandaría una foto de mi init() pero no se si se puede subir fotos de código aca. Si es que se les ocurre que podría ser agradecería cualquier sugerencia.

**Comment by ignaciohermosillacornejo** [comment]
un buen tip para debuggear en C en estas situaciones es usar el comando `assert`. Assert evalua una expresión y solo deja continuar el código si es que la expresión evaluada es verdadera. Por ejemplo si tenemos este programa:

```C
int main() {

    int a = 8;

    assert(a == 8);
    assert(a == 7);

    return 0;
}
```
El primer assert es cierto por lo que el código va a seguir. Después el segundo va a ser falso y tu programa va a detenerse ahi mismo. 

Suerte!

**Comment by alopez7** [comment]
Ojo que si bien tienes tree -> left = NULL si accedes a alg[un atributo de tree -> left, se va a caer ya que NULL no es un puntero válido.

**Comment by gnacrur** [comment]
Antes de usarlo tengo un if revisando si es nulo o no, por lo que eso no debiese ser. ¿Existe la posibilidad de mostrarle mi código a algún ayudante el lunes después o antes de clases? No he logrado solucionarlo aun.

**Comment by alopez7** [comment]
Ok, nos podemos reunir el lunes después de la clase.

**Comment by alopez7** [comment]
Trata de revsisar el código del taller. En el hay un AVL funcional. Podría servirte.

**Comment by gnacrur** [comment]
Hola, al final hice un cambio en como definía mi array que guardaba cada palabra. Ya no tengo el error antiguo pero ahora me sale este :
![image](https://user-images.githubusercontent.com/42191903/65001623-ada66c00-d8c6-11e9-85e1-458b0494e8aa.png)
Quizas es más facil identificar por que pasa el error en este. La linea 115 es la siguiente: 
`uint8_t* palabra = malloc(sizeof(uint8_t)* sopa -> height) ;`
En todo caso gracias a todos por la ayuda!

**Comment by alopez7** [comment]
Ojo que tu error esta en la linea 50 de sopa.c
