### ISSUE TITLE
Output con naivesearch

### ISSUE THREAD

**Issue by jfpena1** [IIC2133-PUC/2019-2#58]
Hola, me pasa que solo para el primer caso, el naivesearch me guarda un archivo .txt con contenido "legible". Para los demas casos, el archivo que se me guarda, tiene solamente caracteres raros  ਰ. 
Adjunto una imagen del tipo de output.
![image](https://user-images.githubusercontent.com/39381457/64898552-e98ac880-d65d-11e9-87b6-3c9dd0fbb816.png)

Queria saber si esto es un error que a alguien mas le ha pasado o si se les ocurre porque podria estar pasando. Me imagino que para obtener el output solucion solamente hay que correr el archivo como venia. Gracias

**Comment by ignaciohermosillacornejo** [comment]
Hola @jfpena1 

Prueba ver en que formato estas viendo el output y prueba con otro.

**Comment by gtvargas** [comment]
A mí me está pasando lo mismo y tampoco sé a qué se debe. Para el test00 el naive y mi código tienen output legible, pero para los demás tests muestra los mismos signos que @jfpena1 .

**Comment by alopez7** [comment]
Chuta, estoy revisando el código base y no tengo idea qué podría estar generando este problema. Por favor si descubren por qué pasa escriban acá. 
¿En qué sistema operativo están trabajando? ¿en qué editor de texto están abriendo el archivo?

**Comment by cacosandon** [comment]
Hola!

Tienen que verlo en algún editor que no sea bloc de notas, al menos eso solucionó mi problema!

**Comment by nacosta-cl** [comment]
Usen notepadd++ u otro editor, porque el bloc de notas puede interpretar mal los caracteres o cambiar las terminaciones LF
