### ISSUE TITLE
Tiempo de ejecución Tarea 1 

### ISSUE THREAD

**Issue by ppotin** [IIC2133-PUC/2019-2#59]
Si tengo un tiempo de 15s en el test mas grande hay penalización? Hay algún margen de error? 🙄🙄

**Comment by ignaciohermosillacornejo** [comment]
Hola! 

Los 10 segundos incluyen el tiempo de margen, por lo que si te demoras 10.000001 segundos se considera incorrecto. Para que te hagas una idea la solución pauta le tomaba un poco mas de 1 segundo en el test grande a si que revisa que estás haciendo para que tu código pase todos los tests.

Saludos
Ignacio

**Comment by alopez7** [comment]
Piensa que se corregirá tu código con 10 segundos en cada test. Si el test más grande toma 15 segundos y el resto toma menos entonces igual tendrás buena nota. El problema sería el más pequeño toma más de 10 segundos.

**Comment by jfpena1** [comment]
Con respecto a esto, los tests que se utlizaran para corregir seran los mismos que nosotros tenemos disponibles? Es decir, si el test mas pesado me corre en 8 segundos debiese estar ok para la correccion, o podria ser que utilizan imagenes aun mas pesadas?

Muchas gracias, Julio.

**Comment by ignaciohermosillacornejo** [comment]
Hola @jfpena1 

No corregimos usando los mismos tests que les damos, pero los tests que usaremos tiene la misma complejidad por lo que debieras andar bien. 

Saludos
Ignacio
