### ISSUE TITLE
Duda creación repositorio personal

### ISSUE THREAD

**Issue by bimartinez** [IIC2133-PUC/2019-2#6]
Hola!

Al ingresar al link que enviaron para crear el repositorio de la tarea se crearon 3 repositorios con mi nombre (me llegaron 3 correos invitandome a distintos repositorios). No se si es algo que me pasó a mi no más o a otras personas le ha pasado.

Saludos!

**Comment by mfbarahona** [comment]
Hola! También me pasó esto, me llegaron 4 mails invitandome a 4 repositorios distintos.

**Comment by ignaciohermosillacornejo** [comment]
Hola! Es un bug de github, solo metanse al primero (el que no tiene -numero) y trabajen ahi.

**Comment by alopez7** [comment]
Por favor también eliminen los sobrantes para no tener repositorios de sobra. El que deben usar es el que tiene formato T0-2019-2-usuario y los que deben eliminar tienen además un número al final.

**Comment by bimartinez** [comment]
Gracias por la respuesta!

Saludos!
