### ISSUE TITLE
Duda sobre dimensiones de las imágenes

### ISSUE THREAD

**Issue by RodrigoNazar** [IIC2133-PUC/2019-2#61]
Hola ✌

Quería preguntar si se puede asumir que los tests en los que se probarán nuestras tareas serán con imágenes cuadradas o no. 

Todas las que vienen en los tests entregados cumplen con la propiedad, por lo que me nació la duda.

Saludos!😎

**Comment by alopez7** [comment]
No puedes asumirlo
