### ISSUE TITLE
Problema incluyendo estructura (creo?)

### ISSUE THREAD

**Issue by Kitaps** [IIC2133-PUC/2019-2#63]
Hola, 

cree mi estructura `Trie` y dentro de ella definí el metoto `trie_init`. 
El problema que tengo es que cuando incluyo el codigo `trie.h` en mi main no me lo reconoce, pero si reconoce el `sopa_init` que creo que esta implementado de la misma forma. 

Que podría estar haciendo mal?
El el error que me tira es 
```
src/decode/main.c:110:15: warning: implicit declaration of function ‘trie_init’; did you mean ‘sopa_init’? [-Wimplicit-function-declaration]
  Trie* trie = trie_init(1);
               ^~~~~~~~~
               sopa_init
```
Edit1: Declarando la funcion antes de llamarla soluciona el problema, pero para el `sopa_init` no la declaran y funciona igual. 

de antemano muchas gracias

**Comment by alopez7** [comment]
Si implementaste trie_init en un archivo trie.h por ejmeplo entonces desde el main debes importar trie.h. Es lo único que se me ocurre que te puede estar pasando.

**Comment by Kitaps** [comment]
Gracias por la respuesta, 

efectivamente faltaba el trie_init en el trie.h 
pense que lo había puesto pero no estaba ahora q revisé. 
Muchas gracias
