### ISSUE TITLE
Error con codigo base

### ISSUE THREAD

**Issue by sjkinast** [IIC2133-PUC/2019-2#64]
Hola, corriendo mi codigo tengo error de "Violación de segmento (`core' generado)", decicidi volver al commit "arreglo fecha entrega enunciado" donde no hay ediciones mias y tengo el mismo error al correr el programa,  a que puede deberse esto?

**Comment by NicolasLahsen** [comment]
Puedes tener malas las rutas de los inputs

**Comment by sjkinast** [comment]
como sería un input valido estando ya en la carpeta de la tarea

**Comment by Pipelao** [comment]
Por ejemplo colocando ./test/test_05.png en vez de ./tests/test_05.png, o que no exista el archivo/carpeta, etc.

**Comment by alopez7** [comment]
Para revisar si se abrió correctamente el archivo puedes ver si el valor de las variables de tipo FILE* son NULL. Si alguno es NULL entonces el path está mal.

**Comment by sjkinast** [comment]
Gracias, y como puedo traer el commit anterior que me crea en la rama HEAD a la master porque haciendo merge de eso no me lo permite
