### ISSUE TITLE
Carpeta "Programa"?

### ISSUE THREAD

**Issue by Calomi** [IIC2133-PUC/2019-2#65]
En el enunciado dice:
- En la carpeta Programa debe encontrarse el codigo.
- Se espera que el codigo compile con make dentro de la carpeta Programa y genere un ejecutable de nombre decode en esa misma carpeta.

En repo (al menos en el mío) esta carpeta no viene por defecto como en la tarea 0, debemos crearla y mover todo ahí? 
o podemos dejarlo con la estructura como está? con el makefile directo en el directorio raíz

**Comment by alopez7** [comment]
Ups, ese es error mío, antes cuando se entregaba informe en el repo había una carpeta programa y otra informe. Debe estar tal como viene el repo.
