### ISSUE TITLE
equivalente a diff de T0

### ISSUE THREAD

**Issue by Kitaps** [IIC2133-PUC/2019-2#67]
Hola, 

hay alguna manera para ver si el output de mi codigo está bien? Así como el metodo diff que nos entregaron en la tarea pasada?

Graicas

**Comment by Pipelao** [comment]
Lo que yo hago al menos es hacer diff entre el archivo que genero con mi suffix trie y el archivo que se genera con el naive search, y luego diff suffix_test.txt naive_test.txt

**Comment by Kitaps** [comment]
Buena idea, pero el naive se demora demasiado jajaja. 
Gracias, haré eso.
