### ISSUE TITLE
Problemas de interfaz gráfica

### ISSUE THREAD

**Issue by alopez7** [IIC2133-PUC/2019-2#69]
Cualquier duda o problema de la interfaz gráfica háganla. Ojalá especifiquen el sistema operativo en el que trabajan y en qué parte falla (instalación de GTK+, compilación de programa, mostrar la interfaz).

**Comment by facortes1** [comment]
No logro instalar el paquete en OS X. Me lanza el error "invalid option: --without-x". No se puede instalar sin ese flag?

**Comment by alopez7** [comment]
Por ahora inténtalo sin el flag. @ignaciohermosillacornejo tal vez te puede ayudar más que yo ya que tiene OS.

**Comment by ignaciohermosillacornejo** [comment]
Hola @facortes1 

Tuvimos el mismo issue el semestre pasado y un alumno encontró la solución, voy a copiar y pegar el issue acá, créditos a @ranieto por encontrar la solución original y a todos los otros alumnos que contribuyeron.

## Comienza issue anterior

### Comentario de: @ranieto

@jiaranda Estaba en lo mismo. Encontré [esta página](https://codeday.me/es/qa/20190220/211851.html) con una supuesta solución.
Corrí la línea `export PKG_CONFIG_PATH=/usr/local/Cellar/cairo/1.12.16/lib/pkgconfig/` (Probablemente la tengas que modificar un poco, por ejemplo mi versión era la 1.16.0), y al intentar compilar me dijo
```
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
```
Así que hice eso, con `export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/`

Después de eso me funcionó :)

edit: y quizás esa primera linea ni siquiera sea necesaria, porque revisé más atrás y ese mismo mensaje me salía desde el comienzo 😅

_Originally posted by @ranieto in https://github.com/IIC2133-PUC/2019-1/issues/10#issuecomment-475406463_


### Comentario de: @nlvargas

@ranieto ¿Cómo se debe modificar el export y cómo saber qué versión se pone? Puse los dos comandos tal cual y no pasó nada en la terminal y sigo teniendo el mismo problema. ("src/beholder/main.c:1:10: fatal error: 'gtk/gtk.h' file not found")

_Originally posted by @nlvargas in https://github.com/IIC2133-PUC/2019-1/issues/10#issuecomment-476652951_

###   Comentario de: @ranieto

@nlvargas Todo esto es asumiendo que el mensaje de error que te sale es el mismo que el mío. El error tiene varias líneas y la primera es `Package libffi was not found in the pkg-config search path.`. Si te sale otra cosa, el problema es otro.

Lo que cambia en el export es la versión del programa, que es parte del path donde está instalada la aplicación. Entonces, si tu versión de `libffi` es la 3.2.0, el comando sería
```
export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.0/lib/pkgconfig/
```
Todo eso son carpetas, incluyendo la versión. Asi que si no sabes qué versión de `libffi` tienes, revisa qué hay en la carpeta!
```
ls /usr/local/Cellar/libffi/
```
Y si por esas cosas de la vida, la carpeta no existe, entonces no tienes instalado `libffi`, y lo puedes instalar con homebrew.
```
brew install libffi
```

_Originally posted by @ranieto in https://github.com/IIC2133-PUC/2019-1/issues/10#issuecomment-476680589_

### Comentario de: @mduhalde1

Hola, qué tal? Seguí todos los pasos que dijeron, es decir: 
1.- `brew install gtk+ gtk+3
`
2.- `export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/
`
 - en mi mac- y aún así me sigue tirando este error: 
`make: *** [obj/beholder/main.o] Error 1
`
Alguien a pesar de seguir todos los pasos le pasó lo mismo ?

_Originally posted by @mduhalde1 in https://github.com/IIC2133-PUC/2019-1/issues/10#issuecomment-477753266_

### Comentario de:  @JoseRomeroi

@mduhalde1 Yo segui todos los pasos, y me sigue apareciendo este error:

` /bin/sh: pkg-config: command not found `
` clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]`
`src/beholder/main.c:1:10: fatal error: 'gtk/gtk.h' file not found`
`#include <gtk/gtk.h>`
         `^~~~~~~~~~~`
`1 error generated.`
`make: *** [obj/beholder/main.o] Error 1`

_Originally posted by @JoseRomeroi in https://github.com/IIC2133-PUC/2019-1/issues/10#issuecomment-477769278_

### Comentario de: @mduhalde1

@fedetaladriz @mduhalde1 Pude hacerlo. Había seguido los pasos anteriores y no me había funcionado. Lo que hice fue lo siguiente:

`brew install pkg-config`

Despues puse make y me tiro el siguiente error:

`Package libffi was not found in the pkg-config search path`

Y lo solucioné con lo que puso @ranieto más arriba.

Ojala les sirva

_Originally posted by @JoseRomeroi in https://github.com/IIC2133-PUC/2019-1/issues/10#issuecomment-478054722_

**Comment by facortes1** [comment]
Me funcionó. Tenía ya instalado las útimas versiones `pkg-config` y `libffi`. Corrí `export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/` y después `brew install gtk+3 gtk+`. Con eso hice make en el directorio y corrió el programa con interfaz gráfica.

**Comment by jfpena1** [comment]
Hola yo tengo Linux Subsystem insatalado en Windows. Al poner ```sudo apt-get install libgtk-3-dev```
me salen varios errores del tipo ```  404  Not Found [IP: 91.189.88.174 80]``` y finalmente el error ```E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?``` 
Trate de hacer ```apt-get update``` y ```--fix-missing``` pero nada funciono.

Nose si estpy haciendo algo mal o es algun error tipico. Muchas gracias

**Comment by alopez7** [comment]
A mi me pasó lo mismo pero se solucionó con el fix missing. Agregaste sudo a ese comando? Te tira algún error?

**Comment by cjmunoz4** [comment]
Hola! Yo tuve el mismo problema que @jfpena1, puse `sudo apt-get update`, después puse `sudo apt-get install --fix-missing` y finalmente volví a correr `sudo apt-get install libgtk-3-dev` y me funcionó.

**Comment by ncasassus** [comment]
Hola! Tuve el mismo problema que @facortes1. Pero no lo pude arreglar con ninguna de las líneas de arriba. Busque mi versión de `libfii` y me apareció que era 3.2.1. Pero `export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/` no me funcionó. Eso si `brew install gtk+3 gtk+` parece completarse bien sin el ` --without-x --without-x11`. Pero al tratar de compilar con `make` me dice que no reconoce <cairo.h>. Tendrá que ver lo del archivo <cairo.h> con ` --without-x --without-x11`? Que debo hacer?

**Comment by ncasassus** [comment]
Hola! Tuve el mismo problema que @facortes1 al principio. Busque la versión de `libffi` que tenía y era el 3.2.1. Luego corrí `export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/` y después `brew install gtk+3 gtk+` (sin la parte de `--without-x --without-x11`). Y no tuve ningún problema. De hecho al correr `make` no me tiró ningún error. Pero al correr el programa, se me cae. No toqué el código y hablando con un amigo me dijo que si debió haber corrido. Puede que sea porque no pude correr `brew install gtk+3 gtk+ --without-x --without-x11`? Qué debo hacer?

**Comment by alopez7** [comment]
@ignaciohermosillacornejo

**Comment by ignaciohermosillacornejo** [comment]
Hola @ncasassus 

Prueba correr el export y después correr `brew install gtk+3 gtk+ --without-x --without-x11`. Si no lo que puedes probar también es instalar `Xcode`

**Comment by ncasassus** [comment]
Hola @ignaciohermosillacornejo! Ya lo intente. Me sigue apareciendo `Error: invalid option: --without-x`. Descargo Xcode del App Store?

**Comment by ignaciohermosillacornejo** [comment]
Si, prueba descargando Xcode del App Store.

**Comment by ncasassus** [comment]
Ya, se demora como 2 horas. Asi que te aviso. Solo con tenerlo instalado debiera funcionar?

**Comment by ignaciohermosillacornejo** [comment]
La verdad es que no se, hay que probar varias cosas hasta que funcione. Si estas muy encima de la entrega haz tu tarea en Ubuntu. Yo instale todas estas cosas hace años y la verdad es que sin tener acceso a tu computador para probar cosas no sabría como ayudarte mucho
