### ISSUE TITLE
Duda pixel exquina tarea-0

### ISSUE THREAD

**Issue by naoliden** [IIC2133-PUC/2019-2#7]
Hola,
Podrían reexplicar que pasa cuando hay que arreglar un pixel del borde de la foto? 
No entendí bien cuales valores hay que tomar para los pixeles de alrededor ni cómo los obtengo. 

Gracias

**Comment by ignaciohermosillacornejo** [comment]
Hola @naoliden 

Creo que una imagen habla más que mil palabras. 


![filtro mediana (2)](https://user-images.githubusercontent.com/11488721/63069365-9ac60380-bee4-11e9-8e64-e7daeac45e95.png)

y para una esquina:

![filtro mediana (3)](https://user-images.githubusercontent.com/11488721/63069422-c3e69400-bee4-11e9-83fb-91fd20fd26c2.png)


Saludos

**Comment by Mariana-Ortega-del-Rio** [comment]
Hola! Me sigue quedando dudas de esto.
Entonces básicamente "creo" nuevos pixeles hacia afuera con los mismos valores que los pixeles adyacentes? Gracias :)

Saludos,
Mariana

**Comment by alopez7** [comment]
Hola mariana, no debes crear los pixeles pasado la esquina pero para los pixeles que están en borde y la esquina debes calcular la mediana como si existieran los pixeles extra de la imagen.

**Comment by lucianoandresch** [comment]
Hola, entonces son 8 casos diferentes?
4 para cada esquina y otros 4 para cada límite del rectángulo? (arriba, abajo, derecha e izquierda)??

Gracias y saludos cordiales

**Comment by alopez7** [comment]
Claro, es distinto para los 8 casos descritos pero se puede programar de manera general sin hacer casos distintos.

**Comment by Kitaps** [comment]
> Claro, es distinto para los 8 casos descritos pero se puede programar de manera general sin hacer casos distintos.

Como? Yo estoy hardcodeando y está quedando horrible

**Comment by felipegarcia98** [comment]
skjajksjka me senti devuelta en intro a la progra con tanto hardcodeo xD

**Comment by alopez7** [comment]
Una forma de hacer el caso borde fácil es de la siguiente forma (en psudocódigo):

Aquí itero sobre los pixeles y para cada pixel itero sobre su vecindad (incluido el mismo pixel). las varoiables neigh_x y neigh_y indican la posicion en x e y del vecino actual. Si se salen de los bordes solo cambio el valor al del límite para leer el pixel correspondiente.
```
for row = 0..rows:
     for col = 0..cols:
          for dx = -1..1:
               for dy = -1..1:
                    neigh_x = col + dx
                    if neigh_x < 0: neigh_x = 0
                    if neigh_y >= cols: neigh_x = cols - 1

                    neigh_y = row + dy
                    if neigh_y < 0: neigh_y = 0
                    if neigh_y >= rows: neigh_y = rows - 1
```

**Comment by ignaciohermosillacornejo** [comment]
Agregando sobre lo que dijo antonio, esos if que tienen se pueden hacer en una linea si usan min y max. Nota que C no tiene min y max definidos por lo que tendrían que crear sus propias funciones.
