### ISSUE TITLE
Dudas de enunciado T2

### ISSUE THREAD

**Issue by alopez7** [IIC2133-PUC/2019-2#70]
Cualquier duda del enunciado para esta tarea 2 pregúntalas acá

**Comment by arbiocanpion** [comment]
Hola!
Leyendo el enunciado de la tarea, me ha surgido una duda, ¿Podemos modificar todos los archivos que queremos dentro de la carpeta baba?, o ,¿Solo podemos modificar los archivos dentro de la carpeta search?

**Comment by alopez7** [comment]
La estructura de los archivo fue hecha para que solo usen lo que hay en search. Incluso dudo que usen lo de BFS. Sin embargo puedes modificar lo que sea si te conviene. Recuerda que solo se corrige el informe.

**Comment by arbiocanpion** [comment]
Gracias!

**Comment by cacosandon** [comment]
Hola!

Con qué largo de tabla de hash deberíamos partir? O queda a disposición de nosotros?

**Comment by alopez7** [comment]
Si, parte con un valor arbitrario. Te recomiendo potencias de 2 ya que es más fácil reservar y liberar memoria con tamaños que son potencias de 2. Por ejemplo 128 es buen tamaño inicial.

**Comment by arbiocanpion** [comment]
Hola!

Una duda respecto al rehashing, cuando en las diapositivas se refieren al n como las diferentes claves guardadas en la tabla, para efectos de la tarea, ¿Podría usar una variación con el n como el numero de elementos guardados en la tabla?.

**Comment by alopez7** [comment]
> Hola!
> 
> Una duda respecto al rehashing, cuando en las diapositivas se refieren al n como las diferentes claves guardadas en la tabla, para efectos de la tarea, ¿Podría usar una variación con el n como el numero de elementos guardados en la tabla?.

No entiendo tu pregunta

**Comment by arbiocanpion** [comment]
Basicamente es, ¿Se puede definir de manera diferente el criterio para hacer rehash?, con esto me refiero a que en vez de usar como indicador el numero de hash guardados dividido el numero total de espacios en el tablero, usar el numero total de elementos guardados en el tablero dividido el numero total de espacios en el tablero.

**Comment by alopez7** [comment]
Asumo que estás hablando de la tabla de hash cuando dices tablero. Lo que propones es lo que sale en las diapos. Cuando el número de elementos guardados en la tabla dividido por el tamaño de la tabla pasa al factor de carga máximo, se hace rehash.

**Comment by arbiocanpion** [comment]
Eso era
¡Muchas gracias!

**Comment by marioreinike** [comment]
Hola! No me quedó muy clara la parte de los experimentos del informe, en esta parte:

**Comment by marioreinike** [comment]
Hola! No me quedó clara la cantidad de "secciones" que deben tener los experimentos, ni cuántos gráficos tengo que poner por experimento. Cuando dice:

> En tu informe tiene que haber una sección por cada experimento y una sección para la versión con Zobrist y en cada sección debes crear ambos gráficos. Además de los gráficos debes explicar a partir de un análisis de los resultados qué valor o configuración es la mejor para la tabla y justificarlo. Finalmente compara la merjor versión de bad hash con Zobrist y escribe tus conclusiones.

Esto quiere decir que debo realizar ambos experimentos para _bad_hash_ y _zobrist_? Y además de eso, en el experimento del factor de carga debo hacer ambos gráficos para cada factor de carga, y en la redistribución de hash, debo hacer ambos gráficos para cada una de las 4 combinaciones?

Lo que entiendo de esto, entonces, es que debo hacer ambos gráficos (distribución y tendencias) 9 veces para cada función de hash. Esto es correcto?

Perdón por lo complicado, espero que se entienda bien lo que quiero decir. Muchas gracias por la ayuda

**Comment by alopez7** [comment]
Los experimentos de factor de carga y de inserción en la tabla solo se hacen con bad hash. En ambos experimentos debes poner ambos gráficos. En cuanto a la versión con zobrist no es necesario experimentar sino solo hacer los gráficos con alguna configuración fija de la tabla. Esto sirve para tener una comparación al momento de escribir las conclusiones.

**Comment by marioreinike** [comment]
Ok muchas gracias!!

**Comment by andreslyon** [comment]
Hola, tengo una duda respecto a la implementación de la tabla de hash. Lo que no me queda claro es que según tengo entendido las tablas con direccionamiento abierto (closed hash with open adressing) no tienen carga, mientras que los con dir. cerrado (open hashing with closed adressing) sí. En en el enunciado sale que debe ser una tabla con dir. abierto y factor de carga. Entonces no tengo claro qué es lo que hay que hacer.
Espero se entienda mi duda.
Gracias

**Comment by alopez7** [comment]
Ambos tipos de tablas tienen factor de carga máximo. Es especialmente importante con las tablas con direccionamiento abierto porque o sino se llena y no se puede insertar más.

**Comment by andreslyon** [comment]
ok, pero a que se refiere el factor de carga en  la tabla con direccionamiento abierto?, debido a que este es una proporción. al menos para el dir. cerrado es, usando la notación de las slides n / m. Cuál sería el n para el dir. abierto?

**Comment by alopez7** [comment]
Lo mismo, el factor de carga máximo de tu tabla es la proporción máxima que hay entre celtas llenas y total de celdas de la tabla. Si tu tabla tirne tamaño 1000 y tienes 700 datos, entonces tu factor de carga es de 0.7

Es por esto que el factor de carga máximo a escoger va entre 0 y 1

**Comment by andreslyon** [comment]
Ahh ya, perfecto, muchas gracias.
:)

**Comment by Tito0906** [comment]
Holaa! Tenía varias dudas sobre la nueva Tabla de Hash y la manera de insertar los datos. Primero, tengo entendido que en la Tabla de Hash que nos entregan existe sólo una lista y la lista se va llenando de manera ascendente sin saltar ningún espacio. Ahora mi pregunta es: ¿Cómo se llena la nueva tabla de Hash? ¿Se rellena de la misma manera ascendente? 
Por lo que entiendo, la función de Hash busca determinar un índice que corresponde a la posición en la que irá el elemento. Según esto, tendría que ir llenando la lista según los índices que entregue bad_hash y no de la manera ascendente actual. ¿Pero que hago en caso de que bad_hash me entregue un índice mayor al largo actual de la lista?

**Comment by alopez7** [comment]
Te recomiendo revisar las clases de tablas de hash porque esto lo deberías tener claro. Pero respondiendo tus tudas:

- La tabla se llena según el valor del hash
- Este valor de hash se transforma usando el método de la multiplicación o el de la división en una posición en la tabla para que no se pase del máximo
- Tu tabla debe funcionar con direccionamiento abierto, esto quiere decir que si una posición ya está en uso, debes buscar otra posición para el elemento a insertar con algún método de sondeo.

**Comment by Tito0906** [comment]
Muchas gracias por responder. Si entiendo que se usa el método de la multiplicación o la división para que no exceda el máximo, pero en el segundo experimento nos piden usar el método de la multiplicación y de la división de manera explícita, algo que no sale para el primer experimento. Ya que no sale para el primer experimento, ¿debo ocupar algún método en específico o da igual?

**Comment by alopez7** [comment]
Ojo que el segundo experimento es una comparación de ambos métodos. Eso no quiere decir que no uses alguno de los métodos antes. En el enunciado dice que primero hay que hacer una tabla de hash funcional y luego se hacen los experimentos. Eso significa que tu tabla debe tener el método de la división o el de la multiplicación ya implementado.

**Comment by Tito0906** [comment]
Ok, muchas gracias por la respuesta!
