### ISSUE TITLE
Arbol 2-4 

### ISSUE THREAD

**Issue by francisca1** [IIC2133-PUC/2019-2#72]
Hola! tengo una duda con la inserción en un arbol 2-4, si inserto y el nodo tiene 4 números ej: 1,2,3,4, ¿Cuál es el nodo que debo subir?, o puede ser cualquiera de los del medio?
Gracias.

**Comment by alopez7** [comment]
Debería subir el 2 o el 3 dependiendo de como se implemente. No es relevante cual suba igual va a cumplir con las propiedades.

**Comment by gatochico** [comment]
Hola, ¿Ocurre lo mismo con el árbol rojo-negro? Que en general hay más de un algoritmo para la inserción, y con tal de que el arbol resultante siga las reglas será considerado correcto? 
Gracias!

**Comment by alopez7** [comment]
No, en un rojo negro las las reglas de rotación son más específicas por lo que siempre hay una opción solamente.
Si se inserta un nodo rojo sobre un nodo rojo se revisa el tío del nodo insertado. Si no hay tío se asume que es negro. 
Si el tío es rojo, se hace un cambio de color y se revisa hacia arriba si se produjo otro conflicto. Si el tío es negro, se rota (rotación doble o simple dependiendo de la disposición de los nodos) y se cambian de color los nodos rotados. En el ejemplo de la clase y en el de la ayudantía se ven todos los casos.
