### ISSUE TITLE
fi en clase Tabla de hash

### ISSUE THREAD

**Issue by Kitaps** [IIC2133-PUC/2019-2#73]
Hola, 

en la clase "10. Tablas de hash" en la pagina 6 abajo sale: 
![image](https://user-images.githubusercontent.com/10112117/65897556-e6921680-e385-11e9-8898-3c6f41e54c42.png)

Que representa ese fi?

Gracias

**Comment by alopez7** [comment]
Hola, la idea es que A sea un irracional. Se ha probado con distintos números irracionales y 1/phi ha funcionado bien. phi es el número áureo (1 + sqrt(5))/2

**Comment by Kitaps** [comment]
Ohhh gracias por la información.
