### ISSUE TITLE
Duda inserción árboles rojo-negro

### ISSUE THREAD

**Issue by fbarrientosj** [IIC2133-PUC/2019-2#74]
Tengo una duda acerca de la inserción en árboles rojo-negro. Como sale en el ppt, si se inserta un nodo rojo y su tío es un nodo rojo, solo se debe cambiar de color los nodos y asegurarse que las reglas de este tipo de árboles se mantengan hacia arriba. No obstante, en la solución de la ayudantía se hacen inversiones a pesar de que el tío sea de color rojo. 
Quería saber cual es la forma correcta de hacerlo ya que me confunde un poco al momento de preparar la I. 

Gracias!

![Screen Shot 2019-10-01 at 12 40 40 PM](https://user-images.githubusercontent.com/37160979/65977817-f7579080-e448-11e9-8b1f-70044475ff4f.png)

![Screen Shot 2019-10-01 at 12 44 11 PM](https://user-images.githubusercontent.com/37160979/65977888-19e9a980-e449-11e9-93d3-e0dfed2d0ac9.png)

**Comment by alopez7** [comment]
Tienes razón, yo me equivoqué en la solución de la ayudantía. La corrijo a más tardar en la noche

**Comment by fbarrientosj** [comment]
Grande gracias !!

**Comment by alopez7** [comment]
Perdón por la demora, lo arreglé
