### ISSUE TITLE
Pregunta ayudantía demostración arboles B

### ISSUE THREAD

**Issue by gnacrur** [IIC2133-PUC/2019-2#75]
Hola, quería ver si me podrían explicar lo que se hace en la pregunta 3 de arboles B de la ayudantía. En particular no entiendo el desarollo correspondiente a la siguiente parte de la pauta:

> Dado un k, el mínimo de nodos que puede tener el árbol es 2k − 1 y su altura máxima es 2 · k, por lo tanto la relación nodos - altura se comporta de manera logarítmica.

Gracias!

**Comment by VicenteVicente** [comment]
Un árbol lleno tiene esta relación entre la altura `h` y la cantidad de nodos `n`:
`n = 2^h-1`
Entonces te dice que dado que en **este caso** su altura máxima `h` es igual a `2 · k`:
`n = 2^(2k)-1` / log ( )
`log(n) = 2k-1`

`h = 2 · k` in `O(log(n))`
y ahí queda un comportamiento logarítmico entre la altura y los nodos (así lo entendí yo, pues creo que la primera `k` y `2 · k` son distintas 😪)

**Comment by alopez7** [comment]
Lo que pasa es que queremos relacionar h con n y tenemos un parámetro extra k con el que podemos relacionarlos.
Dado un k, un árbol tiene entre 2^k-1 y 2^2k-1 nodos y la altura está entre k y 2k. Por lo tanto si depejamos k en ambas relaciones tenemos en el peor caso:
k = log n y k = h/2. 
Por lo tanto h = 2*log n

**Comment by gnacrur** [comment]
Ya perfecto. En todo caso, no tendría entre 2^k-1 + k y 2^2k-1, ya que habría que sumarle la rama larga como explican en la pauta? Si no me equivoco esto igual no efecta porque estamos hablando de ordenes, pero pregunto para saber si estoy entendiendo. Gracias!
