### ISSUE TITLE
Duda XOR en Zobrist Hash en Tarea 2

### ISSUE THREAD

**Issue by naoliden** [IIC2133-PUC/2019-2#76]
Para la tarea estoy siguendo el algoritmo Zobrist y llegué a la parte en que hay que hacer XOR entre mi hash actual y el valor que quiero hashear (no se si lo dije bien).
La pregunta es, cómo se hace eso en C ? si tengo numeros que son uint64_t e ints

**Comment by alopez7** [comment]
Primero que nada, deberían ser ambos númerps un uint64_t. El XOR en C se hace con el símbolo ^ por ejemplo:
```C
hash = hash ^ value;
```
