### ISSUE TITLE
[Duda] - malloc()

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2133-PUC/2019-2#77]
Hola, está bien esto?

`uint64_t* array = malloc(sizeof(uint64_t*) * size);`

, pues al insertarle valores en algunos test me arroja el error:

`Invalid write of size 8`

**Comment by alopez7** [comment]
Debería ser sizeof(uint64_t) sin el *

**Comment by VicenteVicente** [comment]
Buena, muchas gracias!
