### ISSUE TITLE
Duda histograma y contadores - Tarea 2

### ISSUE THREAD

**Issue by JohnTrombon** [IIC2133-PUC/2019-2#78]
Hola,  para crear el histograma debemos crear un arreglo que cuente cuantas veces reviso una celda de mi tabla. Mi duda es, ¿cuento tambien las veces que paso por la celda mientras estoy haciendo el sondeo? Por ejemplo, si mi h(x) da 1, pero haciendo sondeo lineal recorro celdas ocupadas hasta llegar a mi h'(x), digamos 5, ¿Debo sumarle 1 a todos los contadores entre la celda 1 y 5 o solamente a la celda 5?

**Comment by alopez7** [comment]
Si, incluso cuando haces sondeo
