### ISSUE TITLE
duda callgrind, kcachegrind

### ISSUE THREAD

**Issue by JohnTrombon** [IIC2133-PUC/2019-2#79]
Tengo un problema generando el grafico de llamadas, me sale cada funcion de forma independiente y no me dice a que funciones llama. Me parece raro que en cada funcion me sale "called (0)" en lugar de otro numero que supongo debería estar asociado a otra función.
Para generarlo corri valgrind --tool=cachegrind -v [...] y luego kcachegrind para abrir la interfaz.
![image](https://user-images.githubusercontent.com/37162196/66409529-1add8680-e9c7-11e9-8f32-6d26352760b1.png)
¿Hay algo mas que deba hacer para generar un grafico como el del enunciado?

**Comment by alopez7** [comment]
Primero párate en el main para el gráfico. En el mismo gráfico puedes configurar algunos parámetros haciendo click derecho. Las configuraciones te permiten mostrar llamadas que tienen poca frecuencia o que usan poco tiempo y así crece el gráfico. Igual me parece raro que te salga tan poco, voy a tratar de encontrar la solución y te aviso.

**Comment by alopez7** [comment]
¿Podría ser que tu programa se cayó cuando lo usaste con ```--tool=cachegrind```?
No logro encontrar la razón de tu problema.

**Comment by alopez7** [comment]
Si selecciono board_compare en kcachegrind me sale algo muy similar a lo tuyo: 
![image](https://user-images.githubusercontent.com/11396472/66435501-5abe6100-e9fb-11e9-9709-e1fe6f828a9e.png)
Pero si selecciono el main me sale el resto:
![image](https://user-images.githubusercontent.com/11396472/66435535-7590d580-e9fb-11e9-9f00-0c058798ddc5.png)

Lo que te decía con respecto a las configuraciones del gráfico es esto:

![image](https://user-images.githubusercontent.com/11396472/66435591-95c09480-e9fb-11e9-9ef8-99fc2614ceca.png)

Todos esas opciones te dejan ver más detalle del gráfico.

**Comment by JohnTrombon** [comment]
Lo corrí otro día y se arregló solo, yo creo que era porque mercurio estaba en retrógrado. Gracias igual.
