### ISSUE TITLE
Edit de programa base

### ISSUE THREAD

**Issue by Kitaps** [IIC2133-PUC/2019-2#80]
Hola, 

tenía una duda de si es que podemos editar el programa base que se nos entrega, o solamente lo que se nos pide?

Pregunto esto porque para poder hacer y usar la Tabla de Zobrist (para hacer el zobrist hash) necesito crear la tabla y pasarsela a mis funciones. Y no veo donde meterlo para que quede bien. Por lo tanto he estado considerando hacer unos cambios, pero la preocupación que me surge es romper algo que ya está. Además seguramente hay una manera de como hacerlo que no estoy considerando y que usa lo ya implementado.

**Comment by alopez7** [comment]
Puedes editar todo el código que quieras. ¿Quë archivos piensas cambiar?

**Comment by Kitaps** [comment]
Estaba pensando cambiar el main, pero Vicho en clase me explicó que mejor pasarle la tabla de Zobrist a la tabla de hash como una tabla auxiliar.

**Comment by Kitaps** [comment]
Estaba pensando cambiar el main, pero Vicho en clase me explicó que mejor pasarle la tabla de Zobrist a la tabla de hash como una tabla auxiliar. Por lo tanto ya no es necesario editar lo q tenía pensado.

**Comment by chuma9615** [comment]
@Kitaps como le pasaste la tabla de Zobrist a la funcion de hash como una tabla auxiliar?

**Comment by ifcarrera** [comment]
@Kitaps me sumo a la duda de arriba, como se la pasas? :o

**Comment by alopez7** [comment]
Pueden guardar la matriz de números aleatorios como parte del `struct table` o sino crearla en el main y agregarla a las funciones `BFS` y `table_insert`
