### ISSUE TITLE
Sobreescribir puntero

### ISSUE THREAD

**Issue by francisca1** [IIC2133-PUC/2019-2#81]
Hola! tengo una duda, cuando hago rehashing, retorno un nuevo puntero a la tabla, y lo quiero cambiar por el puntero de la tabla anterior, y hago esto:
![imagen](https://user-images.githubusercontent.com/26394880/66518946-b270d100-eabc-11e9-82d7-7e913473fd43.png)
Pero me da segmentation fault, como debo cambiar la referencia?
Gracias

**Comment by francisca1** [comment]
Ya lo solucione, el free se hacía antes >.<

**Comment by francisca1** [comment]
Me acabo de dar cuenta que funcionaba con algunos test y no con todos,alguna sugerencia?

**Comment by francisca1** [comment]
si hago esto:
![imagen](https://user-images.githubusercontent.com/26394880/66581297-42168e00-eb56-11e9-8a9c-c06f3ca1d0da.png)
me toma el cambio solo dentro de la función y no fuera (lo hago en table_insert)

**Comment by alopez7** [comment]
Ok, asumo que Table es tu estructura de datos. Tu quieres remplazar toda la tabla por una nueva pero lo que debes hacer es remplazar el arreglo con los datos de los tableros de la tabla. Digamos que tu arreglo almacena punteros a structs llamama ```Tuple```, sería algo como:

```C
Tuple** new_array = rehash(table);
free(table - > array);
table - > array = new_array;
table - > size *= 2;
```

En este caso la función rehash crea un arreglo nuevo del doble de tamaño, traspasa los datos y retorna el puntero. 

Ese arreglo debe ser creado con malloc

**Comment by francisca1** [comment]
aaaaah okeey, muchas gracias!
