### ISSUE TITLE
Método de la multiplicación

### ISSUE THREAD

**Issue by alopez7** [IIC2133-PUC/2019-2#82]
Me llegaron varias dudas del método de la multiplicación y quería mostrarles cómo lo hice yo para que no tengan problemas.

Si ustedes multiplican un ```uint64_t``` con un ```double```, lo más probable es que tengan una pérdida de presición y les quede un número sin decimales. Por lo tanto para el método de la división les conviene usar un ```uint32_t``` para el hash.
Además les recomiendo hardcodear el número irracional 1/phi en su código en vez de calcularlo ya que calcularlo es más ineficiente y se pierde precisión. El código fibal sería como:

```C
double const = 1.6........;
uint32_t hash = get_hash(board);

double mult = hash * const;
uint64_t entera = (uint64_t) mult;

double decimal = mult - entera;

int position = (int) (decimal * size);
```

**Comment by augustoas** [comment]
Para usar este método mi función de hash me debería retornar un hash de uint32_t??? que lo había hecho con uint64_t.

**Comment by alopez7** [comment]
No tienes que cambiar mucho, solo al llamar la función de hash guarda el valor en un `uint32_t` a pesar de que la función retorne un `uint64_t`

**Comment by augustoas** [comment]
Gracias !

**Comment by ciquezada** [comment]
Una pregunta, ¿¿el metodo de la division no es dividir por el tamañano del arreglo??

**Comment by alopez7** [comment]
No, es sacar módulo del tamaño del arreglo.
