### ISSUE TITLE
Mejor factor de carga

### ISSUE THREAD

**Issue by francisca1** [IIC2133-PUC/2019-2#83]
Hola!, en el enunciado dice que luego de hacer el experimento de los factores de carga, nos quedemos con el mejor, el mejor sería el que ejecuta en menos tiempo el algoritmo? (en el caso mas largo).
gracias.

**Comment by alopez7** [comment]
El que a partir de los datos obtenidos es mejor según el análisis hecho.

**Comment by francisca1** [comment]
se puede usar cualquier test para los experimentos?

**Comment by alopez7** [comment]
Ojalá que no sea de los más chicos para que la tabla se alacanceba duplicar varias veces
