### ISSUE TITLE
badhash y tableros generados

### ISSUE THREAD

**Issue by francisca1** [IIC2133-PUC/2019-2#84]
Hola, para el segundo analisis del tiempo vs cantidad de tablero generado, con bad hash me aparecen cosas raras, para un mismo test, con distinto factor de carga, se generan mas o menos tableros, como en la imagen(las filas son los tests)
![imagen](https://user-images.githubusercontent.com/26394880/66612309-c6d5cc00-eb97-11e9-8f0c-b11ae0d630dd.png)
es esto posible?, con zobrist no me pasa.

**Comment by alopez7** [comment]
No debería ser posible. Algo estás haciendo raro.

**Comment by francisca1** [comment]
lo revise muchas veces, y la verdad no lo veo, la unica opción que veo es que bad_hash pueda darle distinto hash a tableros iguales, lo cual viendo el codigo, si es posible,  ya que si tengo una casilla con pasto->juanito, y en otro tablero juanito->pasto, el bad_hash hace
hash += tipo * i, como el orden es diferente el hash será diferente, mientras que es el mismo tablero, y compare_tablero() primero revisa el hash y luego el tablero.

**Comment by francisca1** [comment]
efectivamente es lo anterior, corri el programa comparando primero los tableros en vez de los hash(se demoro años) y este es el resultado:
![imagen](https://user-images.githubusercontent.com/26394880/66616781-9185aa00-eba8-11e9-91f7-701af9a11d6e.png)

**Comment by alopez7** [comment]
No es posible que pase eso de juanito pasto o pasto juanito.

**Comment by francisca1** [comment]
pero si lo encontraste por otro camino?, ademas en la imagen que puse antes, corri modificando el compare, a que primero revisara los tableros, y ahi si dan iguales, y me dan los mismos numeros que en zobrist

**Comment by alopez7** [comment]
Si es posible que encuentres el mismo estado en distintos caminos y podría tener otro hash por lo que dices. Pero en ejecuciones distintas del mismo test debería darse la exploración de estados de la misma manera por lo que siempre debería explorar el mismo número de estados. Te recomiendo ejecutar tu programa con valgrind porque lo más probable es que sea un problema de memoria.

**Comment by francisca1** [comment]
lo acabo de correr con valgrind y el unico error que arroja en todos los tests viene de bfs.c
![imagen](https://user-images.githubusercontent.com/26394880/66617756-c693fb80-ebac-11e9-82d2-dd795fa2ecf8.png)

**Comment by alopez7** [comment]
Ese no es el error, ese es un leak de memoria, muéstrame lo que hay más arriba.

**Comment by francisca1** [comment]
Ahora funciona, no se porqué, pero funciona
