### ISSUE TITLE
¿Qué son los ejes del histograma?

### ISSUE THREAD

**Issue by sormazabal** [IIC2133-PUC/2019-2#85]
Hola!
Quería tabular los datos de la distribución de búsquedas en las tablas, pero me surgió la duda sobre qué son específicamente los números de los ejes y y x del histograma de ejemplo:

![image](https://user-images.githubusercontent.com/7980453/66613040-6dbb6780-eb9a-11e9-943b-9bf9c5559871.png)

Saludos :D

**Comment by alopez7** [comment]
El eje X son las posiciones de la tabla (puedes agruparlas en en grupos chicos de columnas) y el eje Y es el número de intentos de inserción en esa posición de la tabla. Este gráfico muestra que tanto se agrupan los datos.
