### ISSUE TITLE
Duda tablero Zorbist

### ISSUE THREAD

**Issue by gnacrur** [IIC2133-PUC/2019-2#86]
Hola! No estoy seguros de cuantas posibles piezas debo considerar que hay. En la clase se consideraban que habían 4 tipos de pieza, sin considerar que no hubiese pieza, y por lo tanto, se ponían 4 números aleatorios por espacio. En este caso no entiendo si lo análogo son los 18 posibles personajes o elementos que puede haber en cada espacio o si también hay que considerar la posibles reglas que pueda tener el tablero o si da lo mismo.
Por otra parte, del enunciado entendí que hay una lista en cada uno de estos espacios, pero no logro entender que ponen en esas listas y si nosotros solo tendríamos que considerar el type de la primera celda para poder hashear con Zorbist. Siento que hay algo que no me esta cuadrando así que cualquier aclaración sería más que bienvenida! Gracias.

**Comment by alopez7** [comment]
Son 18 posibles elementos distintos en cada posición por lo que deberías guardar 18 números aleatorios por celda. Hay una lista en cada celda porque pueden haber más de un objeto por celda al mismo tiempo en el tablero. Por lo tanto es una lista. Si te fijas en el `bad_hash` se itera por la lista para obtener todos los valores en cada celda.
