### ISSUE TITLE
Plazo Tarea 2

### ISSUE THREAD

**Issue by tcgarrido** [IIC2133-PUC/2019-2#87]
Hola!

Hablando con otras personas del ramo, vimos que somos varios los que necesitamos un poco más de tiempo para la tarea. Existe la posibilidad de que den más plazo? 😄 

Saludos

**Comment by Mariana-Ortega-del-Rio** [comment]
Hola!

La verdad sería bastante útil si se pudiera.
Gracias de antemano.

Saludos

**Comment by ignaciohermosillacornejo** [comment]
Hola!

Se decidió extender el plazo del código de la tarea hasta el jueves 17 y el viernes 18 el informe.

Saludos

**Comment by gnacrur** [comment]
@ignaciohermosillacornejo Hola, con respecto al plazo del código, esto se refiere a que tengamos listo los dos tipos de sonde, direccionamiento abierto y zobrist? o ya deben estar implementadas las cosas necesarias para poder hacer las comparaciones que nos piden en el informe? Saludos.

**Comment by ignaciohermosillacornejo** [comment]
Hola @gnacrur 

Nos referimos a que el código funcione, no le vamos a poner nota, pero si vamos a evaluar que su código funcione por lo que basta cualquier tipo de implementación de la tabla de hash.
