### ISSUE TITLE
Informe

### ISSUE THREAD

**Issue by ninifdr** [IIC2133-PUC/2019-2#88]
Hola! No entiendo muy bien qué hay que poner en el informe.
En la parte de "Distribución en tabla" solo tengo que probar con bad_hash, con el método que yo quiera, solo con un test y variando el factor de carga máximo? O hay que hacer más combinaciones?
Y en la segunda parte tampoco entiendo si tengo que hacer toooodas las combinaciones entre multiplicación, división, lineal, cuadrático, con bad_hash, con Zobrist o con los dos, etc. Y otra duda, los tableros generados por el programa es la cantidad de veces que hice rehash?
Gracias!

**Comment by chuma9615** [comment]
Tengo la misma duda, siento que no está bien explicitado lo que se espera de nuestro informe, favor de aclarar

**Comment by alopez7** [comment]
En la primera parte debes usar `bad_hash` para encontrar el mejor factor de carga. No es necesario usar todos los tests pero debes tener suficientes tests como para ver una tendencia clara. 
En el segundo experimento debes probar las cuatro combinaciones que se producen al combinar el método de la división y la multiplicación con 2 tipos de sondeo. Esto también se hace usando `bad_hash`. Finalmente para tener un punto de comparación entre los métodos escogidos usando `bad_hash`, debes mostrar con gráficos cómo se comporta `Zobrist`. Para esta última parte no es necesario experimentar, solo es necesario mostrar los resultados para `Zobrist`.

**Comment by alopez7** [comment]
Los tableros generados son todos los tableros explorados por BFS. No confundir tablero con tabla de hash.

**Comment by ninifdr** [comment]
Ya, perfecto gracias!!

**Comment by vjaguilera** [comment]
Hola @alopez7 
Con respecto a la parte de encontrar el mejor factor de carga, no importa el método (multiplicación o división) y el sondeo (lineal, cuadrático o double hashing) utilizado?

**Comment by alopez7** [comment]
No importa, elige primero el factor de carga con cualquier método.

**Comment by sjkinast** [comment]
Hola @alopez7 
El informe no dice que hay que hacer sondeos en el experimento 1 solo probar los distintos factores de carga, además, me parece que no es necesario porque los elementos que se agregan a la tabla de hash se almacenan en la posición count.

**Comment by alopez7** [comment]
Estás mal ahí @sjkinast, ya que la primera parte de la tarea (antes de los experimentos) es implementar una tabla de hash con direccionamiento abierto. Esto implica usar algún tipo de sondeo.
Lo que dices tu es que se almacena en la posición count, asumo que te refieres a la tabla que viene en el código base. Esa no es una tabla de hash, es un arreglo.
