### ISSUE TITLE
Problema punteros y get_random

### ISSUE THREAD

**Issue by gnacrur** [IIC2133-PUC/2019-2#89]
Hola, estoy teniendo un problema que parece ser bastante básico pero no he logrado arreglarlo de ninguna manera. Esto intentando asignarle los valores random a cada bloque de mi tabla zobrist. El problema es que al compilar se queja de que le estoy asignando un int a un puntero:
![image](https://user-images.githubusercontent.com/42191903/66704266-82aa0f00-ecf0-11e9-81ea-209fff6d399e.png)
Entonces lo que hice fue crear una variable puntero que corresponde al puntero de este random pero lo que pasaba ahí fue lo siguiente:
![image](https://user-images.githubusercontent.com/42191903/66704281-b2f1ad80-ecf0-11e9-820e-4641ede38ab2.png)
Lo que no tiene mucho sentido porque todo esta definido como uint64_t. Además intente poniéndole un * antes de ZobristTable para acceder a la memoria donde el puntero apunta, y también trate cambiando la función de random.
Supongo que hay algo que no estoy entendiendo por lo que no puedo solucionar el problema. Aprecio cualquier sugerencia! Gracias.

**Comment by Pipelao** [comment]
¿Cómo definiste la matriz ZobristTable? quizás ahí está el problema. Fijate también en los malloc que haces, puede ser que hayas creado un puntero para recibir el uint64_t.

**Comment by gnacrur** [comment]
No hice malloc y lo declaré así: `uint64_t*** ZobristTable[board-> height][board -> width][19];`
Es necesario hacer malloc? Me olvide mencionar antes que mi problema es que tengo seg fault pero asumía que tenia que ver con ese warning.

**Comment by alopez7** [comment]
Debes hacer malloc...
