### ISSUE TITLE
[Tarea 0] Duda imagenes test respuestas

### ISSUE THREAD

**Issue by haarenas** [IIC2133-PUC/2019-2#9]
Las imagenes que estan en la carpeta de respuestas estan correctas?, por ejemplo tomando la imagen 03 de los test:
![test_03](https://user-images.githubusercontent.com/42160913/63106972-04c8c200-bf52-11e9-96f4-7d95591d2ea6.png)

En la imagen 03 de las respuestas aun se ven algunos pixeles blancos:
![test_03](https://user-images.githubusercontent.com/42160913/63106829-b61b2800-bf51-11e9-8d8a-8ecb2e82d698.png)

Pero la imagen que obtengo yo no tiene pixeles blancos:
![prueba_03new](https://user-images.githubusercontent.com/42160913/63106936-ed89d480-bf51-11e9-9469-5aa413ff3d99.png)

Pregunto porque en el enunciado sale que seran bien estrictos al momento de correr diff x.x

**Comment by ignaciohermosillacornejo** [comment]
Hola! Las imágenes que salen en el enunciado son correctas. Me tinca que estás haciendo más de una pasada a la imagen.

Saludos

**Comment by haarenas** [comment]
Solo la recorro una vez (de la misma forma que el bloque para invertir los colores).

**Comment by sfga** [comment]
@haarenas: ¿Has probado con calcular el pixel faltante usando sólo los pixeles de la imagen original (independiente de que estos sean faltantes o reales)?

Se me ocurre que al incluir pixeles "calculados" (i.e que fueron calculados con el filtro) en la aplicación del filtro para un pixel posterior, la imagen obtenida es distinta a la imagen esperada por los ayudantes.

disclaimer: no soy ayudante :grimacing: jaja

**Comment by ignaciohermosillacornejo** [comment]
Hola @haarenas 

Tal como comenta @sfga estas usando valores calculados para calcular los nuevos valores. La manera en que queremos que hagan esta tarea es que calculen todos los nuevos valores para los pixeles de la imagen y después los actualizen todos de una. 

Saludos

**Comment by nacosta-cl** [comment]
Ese no es Char de Starcraft :smile:?

**Comment by haarenas** [comment]
@sfga @ignaciohermosillacornejo Efectivamente, corrigiendo los pixeles blancos despues de terminar de leer la imagen original se obtiene el output es el esperado, muchas gracias.

PD: Igual sigo pensando que hacer el filtrado de forma dinamica la imagen resultante queda mucho mejor.

**Comment by vichoeq** [comment]
@nacosta-cl Efectivamente! 

@haarenas queda mejor pero ese método depende de el orden en que procesas los pixeles, por ejemplo si recorres por filas o por columnas, o aleatorio. Esto es una propiedad indeseable para lo que estamos pidiendo; no podemos corregir la tarea si hacen eso, ya que existen infinitos resultados "correctos" siendo que todos son distintos y no hay como comprobarlo más que viendo la imagen manualmente. Si lo que quieres es que la imagen quede más limpia y obtener los mismos resultados independiente del orden en que procesas los pixeles la manera correcta de hacerlo es hacer más de una pasada a la imagen, variar el tamaño de la ventana y probar distintas maneras de manejar bordes, entre otros, pero esta tarea no es de procesamiento de imagenes, por lo que no les estamos pidiendo eso.

Por cierto el enunciado dice en **negrita** que los pixeles a usar para la mediana se toman **de la imagen original**.
