### ISSUE TITLE
midiendo tiempos del ejecución

### ISSUE THREAD

**Issue by tomascortes** [IIC2133-PUC/2019-2#91]
Hola, quería hacer un poco más automatico el tomar los tiempos del programa, por lo que quería preguntar si es valido usar la librería "time.h" y la función clock() y medir la diverencia entre el inicio y el fin del main.
Si esto no es representativo, aprovecho de preguntar alguna otra forma recomendada

Gracias

**Comment by alopez7** [comment]
Si se puede. Con eso puedes calcular los ciclos de cpu de la parte del programa que quieres medir. Luego lo multiplicas por los ciclos de cpu por segundo de tu pc. Es una constante de la librería time

**Comment by tomascortes** [comment]
gracias!
