### ISSUE TITLE
Problema rehashing

### ISSUE THREAD

**Issue by Reyza96** [IIC2133-PUC/2019-2#93]
Hola, me pasa que dependiendo del factor de carga y del tamaño del problema mi programa se cae. Se que depende del rehash porque si es que lo hago con una tabla de hash muy grande no se presenta el problema. Lo que es raro es que cuando se cae, ni siquiera se cae en la  función de rehash, simplemente se cae en el sondeo lineal y ni siquiera ocurre en la primera vez que es necesario hacer rehash sino que varía el momento en el que se cae. A que se puede deber esto?

**Comment by alopez7** [comment]
Puede ser que te estás saliendo del largo de la tabla al hacer el sondeo.

**Comment by Reyza96** [comment]
Lo pensé, pero imprimí el table -> count en cada iteración, y en algunos casos se caía antes de estar cerca del tamaño de la tabla

**Comment by Reyza96** [comment]
Puede ser. Lo que no entiendo es porque podría pasar al momento de hacer el 4to rehash y no antes.

**Comment by alopez7** [comment]
Bueno, vas a tener que ejecutar tu programa con valgrind para saber qué parte de tu código tiene problemas se memoria. Una vez que identifiques las líneas que fallan vas a saber mejor cual es el problema.
