### ISSUE TITLE
Problema get_random()

### ISSUE THREAD

**Issue by NicolasLahsen** [IIC2133-PUC/2019-2#94]
Mientras revisaba como funcionaba mi función de hash, me di cuenta que la matriz en tres dimensiones siempre me arrojaba los mismos valores. ¿Por que se podría producir esto?.

Luego de iterar por mi matriz, asigno el valor de esta manera 

`matrixz->matrix[row][col][element] = get_random();`.

Y para printearlos, uso
`printf("%"PRIu64"\n", element)`

**Comment by alopez7** [comment]
no se a que se podría deber. Si no te funciona puedes usar la librería random de C. La puedes ver [aquí](https://www.tutorialspoint.com/c_standard_library/c_function_rand.htm)
