### ISSUE TITLE
Modificar funcion table_init (parametros de entrada

### ISSUE THREAD

**Issue by sfga** [IIC2133-PUC/2019-2#95]
Hola,

   ¿es posible modificar los parametros de entrada de la funcion `Table* table_init(uint8_t height, uint8_t width)`?. Precisamente, me gustaría añadir el parametro 'size' para el largo del arreglo del struct Table. Por otro lado, los parámetros `height` y `width` no se ocupan, por lo que pensaba en eliminarlos de la función. 

  Revisé en el enunciado sobre la duda y sale lo siguiente:
![image](https://user-images.githubusercontent.com/20782942/66805798-506cfd00-eefc-11e9-8b75-45380b012d3d.png)

   Según lo que entiendo, no hay problema en modificar las funciones, siempre y cuando, siga realizando las funciones originales para la que fueron diseñada. De todas maneras, me gustaría que me aclararan la situación al respecto.

Gracias por la atención.

**Comment by sfga** [comment]
Acabo de leer esta issue y creo que esto responde a la duda anterior:

La estructura de los archivo fue hecha para que solo usen lo que hay en search. Incluso dudo que usen lo de BFS. Sin embargo puedes modificar lo que sea si te conviene. Recuerda que solo se corrige el informe.

_Originally posted by @alopez7 in https://github.com/IIC2133-PUC/2019-2/issues/70#issuecomment-538165183_

**Comment by alopez7** [comment]
Si, puedes modificarlo
