### ISSUE TITLE
Contenidos I2 P2

### ISSUE THREAD

**Issue by NicolasLahsen** [IIC2133-PUC/2019-2#96]
Hola! ¿Para la parte 2 de la I2 de mañana entrarán las clases:

- (11) Funciones de Hash
- (12) Grafos & DFS
- (13) Aplicaciones de DFS
- (14) Búsqueda y BFS.

o la clase 11 no entra, por ser evaluada en la tarea? Muchas Gracias!

**Comment by alopez7** [comment]
La clase 11 no entra
