### ISSUE TITLE
Cantidad de gráficos de informe 2

### ISSUE THREAD

**Issue by gnacrur** [IIC2133-PUC/2019-2#97]
Hola, leyendo el informe e issues sobre el tema, aun no me queda tan claro cuantos gráficos en total debemos hacer. No se si además, hay que poner gráficos para cada vez que probemos con uno de los 7 test distintos o no. Ojala puedan aclarar este punto para los que no nos quedó tan claro. Gracias!

**Comment by cjmunoz4** [comment]
Me sumo a la duda, no tengo claro cuándo hay que hacer los histogramas y los gráficos de tendencias ni para qué. Hay que hacerlos tanto para zobrist como para bad hash? Y hay que hacerlos para los experimentos de factor de carga y redistribución de la función de hash? O sólo para alguno de ellos?

**Comment by alopez7** [comment]
En el experimento 1 hay que poner el gráfico de distribución con todos los factores de carga para 1 test mediano o grande y hay que hacer 1 gráfico de comparación entre los factores de carga usando varios tests de distintas didicultades. Para el experimento 2 es lo mismo solo que en vez de los distintos factores de carga, se hace para las 4 combinaciones.
Finalmente se hace un gráfico de distribución para zobrist y un gráfico de comparación entre la mejor versión obtenida en los experiemntos y zobrist

**Comment by ciquezada** [comment]
el unico gráfico de distribución que se debe hacer con zobrist se hace con qué configuracion?

**Comment by alopez7** [comment]
La que sea, la idea es mostrar que una buena función de hash es lo más importante.
