### ISSUE TITLE
Bonus crea tu propio test

### ISSUE THREAD

**Issue by Mariana-Ortega-del-Rio** [IIC2133-PUC/2019-2#98]
Hola!

Tengo una duda en cuanto al bonus de crea tu propio test. Tenía entendido que ayer bastaba con subir una configuración del código para los experimentos, pero para ese bonus también se debía subir el board y rules ayer o como hay que ponerlo en el informe todavía se puede subir o poner en el informe? 

Gracias!

Saludos

**Comment by alopez7** [comment]
Súbelo al repositorio hoy y lo agregas al informe. Lo importante es que yo pueda buscarlo en tu repo y ejecutarlo.

**Comment by Mariana-Ortega-del-Rio** [comment]
Gracias! Lo agregué recién al repo porque cuando vi esto ya eran pasadas las 00 :/
