### ISSUE TITLE
Error: Segmentation fault

### ISSUE THREAD

**Issue by Gorgola22** [IIC2133-PUC/2019-2#99]
Hola! Estoy implementando la parte de división entera + sondeo lineal, y al ejecutar el código me sale en la primera línea "Segmentation fault (core dumped)". Luego al ejecutarlo con valgrind, sale esto:  "Command terminated by signal 11". Alguna idea? Algo que sospecho es que estoy creando un malloc y en el rehash lo libero, habiendo creado uno más grande antes... No se me ocurren más razones de porqué colapsa.

Gracias!

**Comment by alopez7** [comment]
Si malloc no te sirve trata de determinar la parte exacta en la que se cae usando prints. Luego determinas por qué se cae.

**Comment by ciquezada** [comment]
Intenta ver con prints como evoluciona tu hash a medida que los transformas con el sondeo y la division c:

**Comment by Gorgola22** [comment]
Cuando hoy prendo el computador, el código funcionaba. Me funcionó para medir todos los tests de sondeo lineal. Luego comencé a medir el cuadrático: hago make, corro el test y poom... segmentation fault. No sé porqué pasa esto si con valgrind dice que no dejé nada en la memoria, pero aun así siento que es que lleno la ram o algo así que no me deja seguir corriendo los tests. Acabo de reiniciar mi computador y nada :(
